/**
 * Revolution Trading Pros - Icon System (Iconify)
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * All icons are string constants for use with the Icon component.
 * Icons use the Phosphor icon set via @iconify/svelte.
 *
 * Usage:
 * import { Icon, IconUser, IconSettings } from '$lib/icons';
 * <Icon icon={IconUser} size={24} />
 */

// Icon wrapper component
export { default as Icon } from './Icon.svelte';

// =============================================================================
// Phosphor Icon Constants
// =============================================================================

export const IconAB = 'ph:arrows-left-right';
export const IconAB2 = 'ph:arrows-left-right';
export const IconActivity = 'ph:activity';
export const IconActivityHeartbeat = 'ph:heartbeat';
export const IconAdjustments = 'ph:sliders';
export const IconAdjustmentsAlt = 'ph:sliders';
export const IconAdjustmentsHorizontal = 'ph:sliders-horizontal';
export const IconAlertCircle = 'ph:warning-circle';
export const IconAlertTriangle = 'ph:warning';
export const IconAntenna = 'ph:broadcast';
export const IconApi = 'ph:plug';
export const IconApiApp = 'ph:plugs-connected';
export const IconApps = 'ph:squares-four';
export const IconArchive = 'ph:archive-box';
export const IconAlignCenter = 'ph:text-align-center';
export const IconAlignJustified = 'ph:text-align-justify';
export const IconAlignLeft = 'ph:text-align-left';
export const IconAlignRight = 'ph:text-align-right';
export const IconArrowBackUp = 'ph:arrow-u-up-left';
export const IconArrowDown = 'ph:arrow-down';
export const IconArrowDownRight = 'ph:arrow-down-right';
export const IconArrowForwardUp = 'ph:arrow-u-up-right';
export const IconArrowLeft = 'ph:arrow-left';
export const IconArrowNarrowLeft = 'ph:arrow-left';
export const IconArrowNarrowRight = 'ph:arrow-right';
export const IconArrowRight = 'ph:arrow-right';
export const IconArrowUp = 'ph:arrow-up';
export const IconArrowUpRight = 'ph:arrow-up-right';
export const IconArrowsLeftRight = 'ph:arrows-horizontal';
export const IconArrowsSort = 'ph:arrows-down-up';
export const IconArrowsUpDown = 'ph:arrows-down-up';
export const IconArticle = 'ph:article';
export const IconAward = 'ph:trophy';
export const IconBadge = 'ph:seal';
export const IconBell = 'ph:bell';
export const IconBellRinging = 'ph:bell-ringing';
export const IconBlockquote = 'ph:quotes';
export const IconBold = 'ph:text-b';
export const IconBolt = 'ph:lightning';
export const IconBook = 'ph:book';
export const IconBookmark = 'ph:bookmark-simple';
export const IconBookmarkFilled = 'ph:bookmark-simple-fill';
export const IconBox = 'ph:cube';
export const IconBrackets = 'ph:brackets-curly';
export const IconBrain = 'ph:brain';
export const IconBriefcase = 'ph:briefcase';
export const IconBriefcase2 = 'ph:briefcase';
export const IconBrowser = 'ph:browser';
export const IconBug = 'ph:bug';
export const IconBuilding = 'ph:building';
export const IconBuildingBank = 'ph:bank';
export const IconBuildingSkyscraper = 'ph:buildings';
export const IconBuildingStore = 'ph:storefront';
export const IconBulb = 'ph:lightbulb';
export const IconBrandAsana = 'ph:kanban';
export const IconBrandBing = 'ph:magnifying-glass';
export const IconBrandDiscord = 'ph:discord-logo';
export const IconBrandFacebook = 'ph:facebook-logo';
export const IconBrandGithub = 'ph:github-logo';
export const IconBrandGoogle = 'ph:google-logo';
export const IconBrandInstagram = 'ph:instagram-logo';
export const IconBrandLinkedin = 'ph:linkedin-logo';
export const IconBrandMedium = 'ph:medium-logo';
export const IconBrandOpenai = 'ph:robot';
export const IconBrandPaypal = 'ph:paypal-logo';
export const IconBrandReddit = 'ph:reddit-logo';
export const IconBrandTelegram = 'ph:telegram-logo';
export const IconBrandTiktok = 'ph:tiktok-logo';
export const IconBrandTrello = 'ph:trello-logo';
export const IconBrandTwitter = 'ph:twitter-logo';
export const IconBrandVimeo = 'ph:video';
export const IconBrandX = 'ph:x-logo';
export const IconBrandYoutube = 'ph:youtube-logo';
export const IconBroadcast = 'ph:broadcast';
export const IconCalculator = 'ph:calculator';
export const IconCalendar = 'ph:calendar';
export const IconCalendarEvent = 'ph:calendar-check';
export const IconCaretDown = 'ph:caret-down';
export const IconCaretUp = 'ph:caret-up';
export const IconCash = 'ph:money';
export const IconCashBanknote = 'ph:money';
export const IconCategory = 'ph:tag';
export const IconCertificate = 'ph:certificate';
export const IconChartArcs = 'ph:chart-pie';
export const IconChartArea = 'ph:chart-line-up';
export const IconChartBar = 'ph:chart-bar';
export const IconChartCandle = 'ph:chart-line';
export const IconChartDonut = 'ph:chart-donut';
export const IconChartDots = 'ph:chart-scatter';
export const IconChartHistogram = 'ph:chart-bar';
export const IconChartInfographic = 'ph:presentation-chart';
export const IconChartLine = 'ph:chart-line-up';
export const IconChartPie = 'ph:chart-pie';
export const IconChartRadar = 'ph:chart-polar';
export const IconCheck = 'ph:check';
export const IconCheckbox = 'ph:check-square';
export const IconChecklist = 'ph:list-checks';
export const IconCheckupList = 'ph:list-checks';
export const IconChevronDown = 'ph:caret-down';
export const IconChevronLeft = 'ph:caret-left';
export const IconChevronRight = 'ph:caret-right';
export const IconChevronUp = 'ph:caret-up';
export const IconCircleCheck = 'ph:check-circle';
export const IconCircleCheckFilled = 'ph:check-circle-fill';
export const IconCircleX = 'ph:x-circle';
export const IconClick = 'ph:cursor-click';
export const IconClipboard = 'ph:clipboard';
export const IconClock = 'ph:clock';
export const IconCloud = 'ph:cloud';
export const IconCloudUpload = 'ph:cloud-arrow-up';
export const IconCode = 'ph:code';
export const IconCoin = 'ph:coin';
export const IconColorPicker = 'ph:eyedropper';
export const IconCompass = 'ph:compass';
export const IconColumns = 'ph:columns';
export const IconCommand = 'ph:command';
export const IconCopy = 'ph:copy';
export const IconCpu = 'ph:cpu';
export const IconCreditCard = 'ph:credit-card';
export const IconCursor = 'ph:cursor-click';
export const IconCursorText = 'ph:cursor-text';
export const IconCrown = 'ph:crown';
export const IconCsv = 'ph:file-csv';
export const IconCurrencyDollar = 'ph:currency-dollar';
export const IconDashboard = 'ph:gauge';
export const IconDatabase = 'ph:database';
export const IconDeviceAnalytics = 'ph:chart-line-up';
export const IconDeviceDesktopAnalytics = 'ph:desktop';
export const IconDeviceDesktop = 'ph:desktop';
export const IconDeviceFloppy = 'ph:floppy-disk';
export const IconDeviceMobile = 'ph:device-mobile';
export const IconDiamond = 'ph:diamond';
export const IconDeviceTablet = 'ph:device-tablet-speaker';
export const IconDevices = 'ph:devices';
export const IconDiscount = 'ph:percent';
export const IconDots = 'ph:dots-three';
export const IconDotsVertical = 'ph:dots-three-vertical';
export const IconDownload = 'ph:download-simple';
export const IconEdit = 'ph:pencil-simple';
export const IconError404 = 'ph:warning';
export const IconExclamationCircle = 'ph:warning-circle';
export const IconExternalLink = 'ph:arrow-square-out';
export const IconEye = 'ph:eye';
export const IconEyeCheck = 'ph:eye';
export const IconEyeOff = 'ph:eye-slash';
export const IconFile = 'ph:file';
export const IconFileCode = 'ph:file-code';
export const IconFileDiff = 'ph:file-dashed';
export const IconFileDownload = 'ph:file-arrow-down';
export const IconFileAnalytics = 'ph:file-magnifying-glass';
export const IconFileDescription = 'ph:file-text';
export const IconFileExport = 'ph:export';
export const IconFileSpreadsheet = 'ph:file-xls';
export const IconFileText = 'ph:file-text';
export const IconFileTypePdf = 'ph:file-pdf';
export const IconFileTypeDoc = 'ph:file-doc';
export const IconFileZip = 'ph:file-zip';
export const IconFilter = 'ph:funnel';
export const IconFlag = 'ph:flag';
export const IconFlame = 'ph:fire';
export const IconFlask = 'ph:flask';
export const IconFocus = 'ph:crosshair';
export const IconFocusCentered = 'ph:crosshair-simple';
export const IconFingerprint = 'ph:fingerprint';
export const IconFingerprintScan = 'ph:fingerprint';
export const IconFolder = 'ph:folder';
export const IconFolderPlus = 'ph:folder-plus';
export const IconForms = 'ph:note-pencil';
export const IconGauge = 'ph:gauge';
export const IconGif = 'ph:gif';
export const IconGift = 'ph:gift';
export const IconGitMerge = 'ph:git-merge';
export const IconGridDots = 'ph:dots-nine';
export const IconGripVertical = 'ph:dots-six-vertical';
export const IconH1 = 'ph:text-h-one';
export const IconH2 = 'ph:text-h-two';
export const IconH3 = 'ph:text-h-three';
export const IconHeart = 'ph:heart';
export const IconHeadset = 'ph:headset';
export const IconHeartbeat = 'ph:heartbeat';
export const IconHelp = 'ph:question';
export const IconHistory = 'ph:clock-counter-clockwise';
export const IconHome = 'ph:house';
export const IconHomeDollar = 'ph:house';
export const IconHourglass = 'ph:hourglass';
export const IconId = 'ph:identification-card';
export const IconInbox = 'ph:tray';
export const IconInfoCircle = 'ph:info';
export const IconItalic = 'ph:text-italic';
export const IconJson = 'ph:brackets-curly';
export const IconKey = 'ph:key';
export const IconKeyboard = 'ph:keyboard';
export const IconLanguage = 'ph:translate';
export const IconLayout2 = 'ph:layout';
export const IconLayoutDashboard = 'ph:squares-four';
export const IconLayoutDistributeHorizontal = 'ph:columns';
export const IconLayoutGrid = 'ph:grid-four';
export const IconLayoutGridAdd = 'ph:grid-four';
export const IconLayoutKanban = 'ph:kanban';
export const IconLayoutNavbarCollapse = 'ph:sidebar';
export const IconLayoutRows = 'ph:rows';
export const IconLeaf = 'ph:leaf';
export const IconLink = 'ph:link';
export const IconList = 'ph:list';
export const IconListCheck = 'ph:list-checks';
export const IconListDetails = 'ph:list-dashes';
export const IconListNumbers = 'ph:list-numbers';
export const IconListTree = 'ph:tree-structure';
export const IconLive = 'ph:broadcast';
export const IconLoader = 'ph:spinner';
export const IconLoader2 = 'ph:spinner-gap';
export const IconLocation = 'ph:map-pin';
export const IconLock = 'ph:lock';
export const IconLockOpen = 'ph:lock-open';
export const IconLockSquare = 'ph:lock';
export const IconLogin = 'ph:sign-in';
export const IconLogout = 'ph:sign-out';
export const IconMail = 'ph:envelope';
export const IconMailCheck = 'ph:envelope';
export const IconMailFast = 'ph:paper-plane-tilt';
export const IconMailForward = 'ph:share';
export const IconMailOpened = 'ph:envelope-open';
export const IconMap = 'ph:map-trifold';
export const IconMapPin = 'ph:map-pin';
export const IconMapPin2 = 'ph:map-pin-line';
export const IconMapPins = 'ph:map-pin';
export const IconMaximize = 'ph:arrows-out';
export const IconMedal = 'ph:medal';
export const IconMenu = 'ph:list';
export const IconMenu2 = 'ph:list';
export const IconMessage = 'ph:chat';
export const IconMessageCircle = 'ph:chat-circle';
export const IconMinimize = 'ph:arrows-in';
export const IconMinus = 'ph:minus';
export const IconMoneybag = 'ph:money';
export const IconMoodSmile = 'ph:smiley';
export const IconMoon = 'ph:moon';
export const IconMouse = 'ph:mouse';
export const IconNavigation = 'ph:navigation-arrow';
export const IconNetwork = 'ph:graph';
export const IconNews = 'ph:newspaper';
export const IconNote = 'ph:note';
export const IconNotes = 'ph:notepad';
export const IconPackage = 'ph:package';
export const IconPalette = 'ph:palette';
export const IconPaperclip = 'ph:paperclip';
export const IconPdf = 'ph:file-pdf';
export const IconPencil = 'ph:pencil';
export const IconPercentage = 'ph:percent';
export const IconPhone = 'ph:phone';
export const IconPhoto = 'ph:image';
export const IconPhotoFilled = 'ph:image-fill';
export const IconPigMoney = 'ph:piggy-bank';
export const IconPin = 'ph:push-pin';
export const IconPinFilled = 'ph:push-pin-fill';
export const IconPlay = 'ph:play';
export const IconPointer = 'ph:cursor';
export const IconPictureInPicture = 'ph:picture-in-picture';
export const IconPictureInPictureOn = 'ph:picture-in-picture';
export const IconPlayerPause = 'ph:pause';
export const IconPlayerPlay = 'ph:play';
export const IconPlayerStop = 'ph:stop';
export const IconPlugConnected = 'ph:plug';
export const IconPlugConnectedX = 'ph:plugs';
export const IconPlugOff = 'ph:plugs';
export const IconPlus = 'ph:plus';
export const IconProgress = 'ph:spinner';
export const IconProgressCheck = 'ph:check-circle';
export const IconQrcode = 'ph:qr-code';
export const IconQuestionMark = 'ph:question';
export const IconRadar = 'ph:radar';
export const IconRadar2 = 'ph:radar';
export const IconRotate = 'ph:arrow-counter-clockwise';
export const IconRotateClockwise = 'ph:arrow-clockwise';
export const IconQuote = 'ph:quotes';
export const IconReceipt = 'ph:receipt';
export const IconReceiptTax = 'ph:receipt';
export const IconRefresh = 'ph:arrow-counter-clockwise';
export const IconReload = 'ph:arrows-clockwise';
export const IconRepeat = 'ph:repeat';
export const IconReportAnalytics = 'ph:chart-line-up';
export const IconRobot = 'ph:robot';
export const IconRocket = 'ph:rocket-launch';
export const IconRoute = 'ph:path';
export const IconScan = 'ph:scan';
export const IconScale = 'ph:scales';
export const IconSchool = 'ph:graduation-cap';
export const IconSearch = 'ph:magnifying-glass';
export const IconSeedling = 'ph:plant';
export const IconSend = 'ph:paper-plane-tilt';
export const IconSeo = 'ph:magnifying-glass';
export const IconServer = 'ph:hard-drives';
export const IconSettings = 'ph:gear';
export const IconShare = 'ph:share-network';
export const IconShield = 'ph:shield';
export const IconShieldCheck = 'ph:shield-check';
export const IconShieldLock = 'ph:shield-checkered';
export const IconShoppingCart = 'ph:shopping-cart';
export const IconSitemap = 'ph:tree-structure';
export const IconSortAscending = 'ph:sort-ascending';
export const IconSortDescending = 'ph:sort-descending';
export const IconSpacingVertical = 'ph:arrows-vertical';
export const IconSparkles = 'ph:sparkle';
export const IconSpeakerphone = 'ph:megaphone';
export const IconSpeedboat = 'ph:boat';
export const IconSquare = 'ph:square';
export const IconSquareCheck = 'ph:check-square';
export const IconSquareRounded = 'ph:square';
export const IconSquareRoundedCheck = 'ph:check-square';
export const IconSquareRoundedCheckFilled = 'ph:check-square-fill';
export const IconSquareRoundedMinus = 'ph:minus-square';
export const IconSquareRoundedPlus = 'ph:plus-square';
export const IconSquareRoundedX = 'ph:x-square';
export const IconStack = 'ph:stack';
export const IconStack2 = 'ph:stack';
export const IconStar = 'ph:star';
export const IconStarFilled = 'ph:star-fill';
export const IconStarOff = 'ph:star';
export const IconStrikethrough = 'ph:text-strikethrough';
export const IconSubtask = 'ph:tree-structure';
export const IconSunHigh = 'ph:sun';
export const IconTable = 'ph:table';
export const IconTag = 'ph:tag';
export const IconTags = 'ph:tags';
export const IconTarget = 'ph:target';
export const IconTargetArrow = 'ph:target';
export const IconTemplate = 'ph:layout';
export const IconTerminal = 'ph:terminal';
export const IconTestPipe = 'ph:test-tube';
export const IconTestPipe2 = 'ph:test-tube';
export const IconTextCaption = 'ph:subtitles';
export const IconThumbUp = 'ph:thumbs-up';
export const IconTicket = 'ph:ticket';
export const IconTimeline = 'ph:timeline';
export const IconToggleLeft = 'ph:toggle-left';
export const IconToggleRight = 'ph:toggle-right';
export const IconTool = 'ph:wrench';
export const IconTools = 'ph:wrench';
export const IconTrash = 'ph:trash';
export const IconTrendingDown = 'ph:trend-down';
export const IconTrendingDown2 = 'ph:trend-down';
export const IconTrendingDown3 = 'ph:trend-down';
export const IconTrendingUp = 'ph:trend-up';
export const IconTrendingUp2 = 'ph:trend-up';
export const IconTrendingUp3 = 'ph:trend-up';
export const IconTrophy = 'ph:trophy';
export const IconUnderline = 'ph:text-underline';
export const IconUpload = 'ph:upload-simple';
export const IconUser = 'ph:user';
export const IconUserCheck = 'ph:user-check';
export const IconUserCircle = 'ph:user-circle';
export const IconUserEdit = 'ph:user-gear';
export const IconUserMinus = 'ph:user-minus';
export const IconUserPlus = 'ph:user-plus';
export const IconUserOff = 'ph:user-minus';
export const IconUsers = 'ph:users';
export const IconUsersGroup = 'ph:users-three';
export const IconBan = 'ph:prohibit';
export const IconVideo = 'ph:video-camera';
export const IconVolume = 'ph:speaker-high';
export const IconVolumeOff = 'ph:speaker-slash';
export const IconWallet = 'ph:wallet';
export const IconWand = 'ph:magic-wand';
export const IconWaveSine = 'ph:wave-sine';
export const IconWebhook = 'ph:webhooks-logo';
export const IconWifi = 'ph:wifi-high';
export const IconWorld = 'ph:globe';
export const IconWorldWww = 'ph:globe';
export const IconX = 'ph:x';
export const IconZoomCheck = 'ph:magnifying-glass';
export const IconZoomIn = 'ph:magnifying-glass-plus';
export const IconZoomMoney = 'ph:magnifying-glass';
export const IconZoomOut = 'ph:magnifying-glass-minus';

// Aliases
export const IconArrowForward = IconArrowForwardUp;
export const IconBrandTradingview = IconChartCandle;
export const IconChecks = IconChecklist;
export const IconSave = IconDeviceFloppy;

// =============================================================================
// Custom Local SVG Icons (lightweight alternatives)
// =============================================================================

export { default as IconPlusLocal } from './IconPlus.svelte';
export { default as IconXLocal } from './IconX.svelte';
export { default as IconChevronDownLocal } from './IconChevronDown.svelte';
export { default as IconChevronLeftLocal } from './IconChevronLeft.svelte';
export { default as IconChevronRightLocal } from './IconChevronRight.svelte';
export { default as IconCheckLocal } from './IconCheck.svelte';
export { default as IconMinusLocal } from './IconMinus.svelte';
export { default as IconPhotoLocal } from './IconPhoto.svelte';
export { default as IconVideoLocal } from './IconVideo.svelte';
export { default as IconCodeLocal } from './IconCode.svelte';
export { default as IconListLocal } from './IconList.svelte';
export { default as IconPlayerPlayLocal } from './IconPlayerPlay.svelte';
export { default as IconPlayerPauseLocal } from './IconPlayerPause.svelte';
export { default as IconVolumeLocal } from './IconVolume.svelte';
export { default as IconVolumeOffLocal } from './IconVolumeOff.svelte';
export { default as IconMaximizeLocal } from './IconMaximize.svelte';
export { default as IconCopyLocal } from './IconCopy.svelte';
export { default as IconLinkLocal } from './IconLink.svelte';
export { default as IconLayoutGridLocal } from './IconLayoutGrid.svelte';
export { default as IconColumnsLocal } from './IconColumns.svelte';
export { default as IconStarLocal } from './IconStar.svelte';
export { default as IconCircleLocal } from './IconCircle.svelte';
export { default as IconSquareLocal } from './IconSquare.svelte';
export { default as IconSparklesLocal } from './IconSparkles.svelte';

import type { Component } from 'svelte';

/**
 * Type-safe icon component type
 * Use this for props that accept icon components
 */
export type IconComponent = Component<{
	size?: number;
	color?: string;
	stroke?: number;
	class?: string;
}>;
