/**
 * Revolution Trading Pros - Icon System (Iconify)
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * All icons are string constants for use with the Icon component.
 * Icons use the Tabler icon set via @iconify/svelte.
 *
 * Usage:
 * import { Icon, IconUser, IconSettings } from '$lib/icons';
 * <Icon icon={IconUser} size={24} />
 */

// Icon wrapper component
export { default as Icon } from './Icon.svelte';

// =============================================================================
// Tabler Icon Constants
// =============================================================================

export const IconAB = 'tabler:a-b';
export const IconAB2 = 'tabler:a-b-2';
export const IconActivity = 'tabler:activity';
export const IconActivityHeartbeat = 'tabler:activity-heartbeat';
export const IconAdjustments = 'tabler:adjustments';
export const IconAdjustmentsAlt = 'tabler:adjustments-alt';
export const IconAdjustmentsHorizontal = 'tabler:adjustments-horizontal';
export const IconAlertCircle = 'tabler:alert-circle';
export const IconAlertTriangle = 'tabler:alert-triangle';
export const IconAntenna = 'tabler:antenna';
export const IconApi = 'tabler:api';
export const IconApiApp = 'tabler:api-app';
export const IconApps = 'tabler:apps';
export const IconArchive = 'tabler:archive';
export const IconAlignCenter = 'tabler:align-center';
export const IconAlignJustified = 'tabler:align-justified';
export const IconAlignLeft = 'tabler:align-left';
export const IconAlignRight = 'tabler:align-right';
export const IconArrowBackUp = 'tabler:arrow-back-up';
export const IconArrowDown = 'tabler:arrow-down';
export const IconArrowDownRight = 'tabler:arrow-down-right';
export const IconArrowForwardUp = 'tabler:arrow-forward-up';
export const IconArrowLeft = 'tabler:arrow-left';
export const IconArrowNarrowLeft = 'tabler:arrow-narrow-left';
export const IconArrowNarrowRight = 'tabler:arrow-narrow-right';
export const IconArrowRight = 'tabler:arrow-right';
export const IconArrowUp = 'tabler:arrow-up';
export const IconArrowUpRight = 'tabler:arrow-up-right';
export const IconArrowsLeftRight = 'tabler:arrows-left-right';
export const IconArrowsSort = 'tabler:arrows-sort';
export const IconArrowsUpDown = 'tabler:arrows-up-down';
export const IconArticle = 'tabler:article';
export const IconAward = 'tabler:award';
export const IconBadge = 'tabler:badge';
export const IconBell = 'tabler:bell';
export const IconBellRinging = 'tabler:bell-ringing';
export const IconBlockquote = 'tabler:blockquote';
export const IconBold = 'tabler:bold';
export const IconBolt = 'tabler:bolt';
export const IconBook = 'tabler:book';
export const IconBookmark = 'tabler:bookmark';
export const IconBookmarkFilled = 'tabler:bookmark-filled';
export const IconBox = 'tabler:box';
export const IconBrackets = 'tabler:brackets';
export const IconBrain = 'tabler:brain';
export const IconBriefcase = 'tabler:briefcase';
export const IconBriefcase2 = 'tabler:briefcase-2';
export const IconBrowser = 'tabler:browser';
export const IconBug = 'tabler:bug';
export const IconBuilding = 'tabler:building';
export const IconBuildingBank = 'tabler:building-bank';
export const IconBuildingSkyscraper = 'tabler:building-skyscraper';
export const IconBuildingStore = 'tabler:building-store';
export const IconBulb = 'tabler:bulb';
export const IconBrandAsana = 'tabler:brand-asana';
export const IconBrandBing = 'tabler:brand-bing';
export const IconBrandDiscord = 'tabler:brand-discord';
export const IconBrandFacebook = 'tabler:brand-facebook';
export const IconBrandGithub = 'tabler:brand-github';
export const IconBrandGoogle = 'tabler:brand-google';
export const IconBrandInstagram = 'tabler:brand-instagram';
export const IconBrandLinkedin = 'tabler:brand-linkedin';
export const IconBrandMedium = 'tabler:brand-medium';
export const IconBrandOpenai = 'tabler:brand-openai';
export const IconBrandPaypal = 'tabler:brand-paypal';
export const IconBrandReddit = 'tabler:brand-reddit';
export const IconBrandTelegram = 'tabler:brand-telegram';
export const IconBrandTiktok = 'tabler:brand-tiktok';
export const IconBrandTrello = 'tabler:brand-trello';
export const IconBrandTwitter = 'tabler:brand-twitter';
export const IconBrandVimeo = 'tabler:brand-vimeo';
export const IconBrandX = 'tabler:brand-x';
export const IconBrandYoutube = 'tabler:brand-youtube';
export const IconBroadcast = 'tabler:broadcast';
export const IconCalculator = 'tabler:calculator';
export const IconCalendar = 'tabler:calendar';
export const IconCalendarEvent = 'tabler:calendar-event';
export const IconCaretDown = 'tabler:caret-down';
export const IconCaretUp = 'tabler:caret-up';
export const IconCash = 'tabler:cash';
export const IconCashBanknote = 'tabler:cash-banknote';
export const IconCategory = 'tabler:category';
export const IconCertificate = 'tabler:certificate';
export const IconChartArcs = 'tabler:chart-arcs';
export const IconChartArea = 'tabler:chart-area';
export const IconChartBar = 'tabler:chart-bar';
export const IconChartCandle = 'tabler:chart-candle';
export const IconChartDonut = 'tabler:chart-donut';
export const IconChartDots = 'tabler:chart-dots';
export const IconChartHistogram = 'tabler:chart-histogram';
export const IconChartInfographic = 'tabler:chart-infographic';
export const IconChartLine = 'tabler:chart-line';
export const IconChartPie = 'tabler:chart-pie';
export const IconChartRadar = 'tabler:chart-radar';
export const IconCheck = 'tabler:check';
export const IconCheckbox = 'tabler:checkbox';
export const IconChecklist = 'tabler:checklist';
export const IconCheckupList = 'tabler:checkup-list';
export const IconChevronDown = 'tabler:chevron-down';
export const IconChevronLeft = 'tabler:chevron-left';
export const IconChevronRight = 'tabler:chevron-right';
export const IconChevronUp = 'tabler:chevron-up';
export const IconCircleCheck = 'tabler:circle-check';
export const IconCircleCheckFilled = 'tabler:circle-check-filled';
export const IconCircleX = 'tabler:circle-x';
export const IconClick = 'tabler:click';
export const IconClipboard = 'tabler:clipboard';
export const IconClock = 'tabler:clock';
export const IconCloud = 'tabler:cloud';
export const IconCloudUpload = 'tabler:cloud-upload';
export const IconCode = 'tabler:code';
export const IconCoin = 'tabler:coin';
export const IconColorPicker = 'tabler:color-picker';
export const IconCompass = 'tabler:compass';
export const IconColumns = 'tabler:columns';
export const IconCommand = 'tabler:command';
export const IconCopy = 'tabler:copy';
export const IconCpu = 'tabler:cpu';
export const IconCreditCard = 'tabler:credit-card';
export const IconCursor = 'tabler:click';
export const IconCursorText = 'tabler:cursor-text';
export const IconCrown = 'tabler:crown';
export const IconCsv = 'tabler:csv';
export const IconCurrencyDollar = 'tabler:currency-dollar';
export const IconDashboard = 'tabler:dashboard';
export const IconDatabase = 'tabler:database';
export const IconDeviceAnalytics = 'tabler:device-analytics';
export const IconDeviceDesktopAnalytics = 'tabler:device-desktop-analytics';
export const IconDeviceDesktop = 'tabler:device-desktop';
export const IconDeviceFloppy = 'tabler:device-floppy';
export const IconDeviceMobile = 'tabler:device-mobile';
export const IconDiamond = 'tabler:diamond';
export const IconDeviceTablet = 'tabler:device-tablet';
export const IconDevices = 'tabler:devices';
export const IconDiscount = 'tabler:discount';
export const IconDots = 'tabler:dots';
export const IconDotsVertical = 'tabler:dots-vertical';
export const IconDownload = 'tabler:download';
export const IconEdit = 'tabler:edit';
export const IconError404 = 'tabler:error-404';
export const IconExclamationCircle = 'tabler:exclamation-circle';
export const IconExternalLink = 'tabler:external-link';
export const IconEye = 'tabler:eye';
export const IconEyeCheck = 'tabler:eye-check';
export const IconEyeOff = 'tabler:eye-off';
export const IconFile = 'tabler:file';
export const IconFileCode = 'tabler:file-code';
export const IconFileDiff = 'tabler:file-diff';
export const IconFileDownload = 'tabler:file-download';
export const IconFileAnalytics = 'tabler:file-analytics';
export const IconFileDescription = 'tabler:file-description';
export const IconFileExport = 'tabler:file-export';
export const IconFileSpreadsheet = 'tabler:file-spreadsheet';
export const IconFileText = 'tabler:file-text';
export const IconFileTypePdf = 'tabler:file-type-pdf';
export const IconFileTypeDoc = 'tabler:file-type-doc';
export const IconFileZip = 'tabler:file-zip';
export const IconFilter = 'tabler:filter';
export const IconFlag = 'tabler:flag';
export const IconFlame = 'tabler:flame';
export const IconFlask = 'tabler:flask';
export const IconFocus = 'tabler:focus';
export const IconFocusCentered = 'tabler:focus-centered';
export const IconFingerprint = 'tabler:fingerprint';
export const IconFingerprintScan = 'tabler:fingerprint-scan';
export const IconFolder = 'tabler:folder';
export const IconFolderPlus = 'tabler:folder-plus';
export const IconForms = 'tabler:forms';
export const IconGauge = 'tabler:gauge';
export const IconGif = 'tabler:gif';
export const IconGift = 'tabler:gift';
export const IconGitMerge = 'tabler:git-merge';
export const IconGridDots = 'tabler:grid-dots';
export const IconGripVertical = 'tabler:grip-vertical';
export const IconH1 = 'tabler:h-1';
export const IconH2 = 'tabler:h-2';
export const IconH3 = 'tabler:h-3';
export const IconHeart = 'tabler:heart';
export const IconHeadset = 'tabler:headset';
export const IconHeartbeat = 'tabler:heartbeat';
export const IconHelp = 'tabler:help';
export const IconHistory = 'tabler:history';
export const IconHome = 'tabler:home';
export const IconHomeDollar = 'tabler:home-dollar';
export const IconHourglass = 'tabler:hourglass';
export const IconId = 'tabler:id';
export const IconInbox = 'tabler:inbox';
export const IconInfoCircle = 'tabler:info-circle';
export const IconItalic = 'tabler:italic';
export const IconJson = 'tabler:json';
export const IconKey = 'tabler:key';
export const IconKeyboard = 'tabler:keyboard';
export const IconLanguage = 'tabler:language';
export const IconLayout2 = 'tabler:layout-2';
export const IconLayoutDashboard = 'tabler:layout-dashboard';
export const IconLayoutDistributeHorizontal = 'tabler:layout-distribute-horizontal';
export const IconLayoutGrid = 'tabler:layout-grid';
export const IconLayoutGridAdd = 'tabler:layout-grid-add';
export const IconLayoutKanban = 'tabler:layout-kanban';
export const IconLayoutNavbarCollapse = 'tabler:layout-navbar-collapse';
export const IconLayoutRows = 'tabler:layout-rows';
export const IconLeaf = 'tabler:leaf';
export const IconLink = 'tabler:link';
export const IconList = 'tabler:list';
export const IconListCheck = 'tabler:list-check';
export const IconListDetails = 'tabler:list-details';
export const IconListNumbers = 'tabler:list-numbers';
export const IconListTree = 'tabler:list-tree';
export const IconLive = 'tabler:live-photo';
export const IconLoader = 'tabler:loader';
export const IconLoader2 = 'tabler:loader-2';
export const IconLocation = 'tabler:location';
export const IconLock = 'tabler:lock';
export const IconLockOpen = 'tabler:lock-open';
export const IconLockSquare = 'tabler:lock-square';
export const IconLogin = 'tabler:login';
export const IconLogout = 'tabler:logout';
export const IconMail = 'tabler:mail';
export const IconMailCheck = 'tabler:mail-check';
export const IconMailFast = 'tabler:mail-fast';
export const IconMailForward = 'tabler:mail-forward';
export const IconMailOpened = 'tabler:mail-opened';
export const IconMap = 'tabler:map';
export const IconMapPin = 'tabler:map-pin';
export const IconMapPin2 = 'tabler:map-pin-2';
export const IconMapPins = 'tabler:map-pins';
export const IconMaximize = 'tabler:maximize';
export const IconMedal = 'tabler:medal';
export const IconMenu = 'tabler:menu';
export const IconMenu2 = 'tabler:menu-2';
export const IconMessage = 'tabler:message';
export const IconMessageCircle = 'tabler:message-circle';
export const IconMinimize = 'tabler:minimize';
export const IconMinus = 'tabler:minus';
export const IconMoneybag = 'tabler:moneybag';
export const IconMoodSmile = 'tabler:mood-smile';
export const IconMoon = 'tabler:moon';
export const IconMouse = 'tabler:mouse';
export const IconNavigation = 'tabler:navigation';
export const IconNetwork = 'tabler:network';
export const IconNews = 'tabler:news';
export const IconNote = 'tabler:note';
export const IconNotes = 'tabler:notes';
export const IconPackage = 'tabler:package';
export const IconPalette = 'tabler:palette';
export const IconPaperclip = 'tabler:paperclip';
export const IconPdf = 'tabler:pdf';
export const IconPencil = 'tabler:pencil';
export const IconPercentage = 'tabler:percentage';
export const IconPhone = 'tabler:phone';
export const IconPhoto = 'tabler:photo';
export const IconPhotoFilled = 'tabler:photo-filled';
export const IconPigMoney = 'tabler:pig-money';
export const IconPin = 'tabler:pin';
export const IconPinFilled = 'tabler:pin-filled';
export const IconPlay = 'tabler:player-play';
export const IconPointer = 'tabler:pointer';
export const IconPictureInPicture = 'tabler:picture-in-picture';
export const IconPictureInPictureOn = 'tabler:picture-in-picture-on';
export const IconPlayerPause = 'tabler:player-pause';
export const IconPlayerPlay = 'tabler:player-play';
export const IconPlayerStop = 'tabler:player-stop';
export const IconPlugConnected = 'tabler:plug-connected';
export const IconPlugConnectedX = 'tabler:plug-connected-x';
export const IconPlugOff = 'tabler:plug-off';
export const IconPlus = 'tabler:plus';
export const IconProgress = 'tabler:progress';
export const IconProgressCheck = 'tabler:progress-check';
export const IconQrcode = 'tabler:qrcode';
export const IconQuestionMark = 'tabler:question-mark';
export const IconRadar = 'tabler:radar';
export const IconRadar2 = 'tabler:radar-2';
export const IconRotate = 'tabler:rotate';
export const IconRotateClockwise = 'tabler:rotate-clockwise';
export const IconQuote = 'tabler:quote';
export const IconReceipt = 'tabler:receipt';
export const IconReceiptTax = 'tabler:receipt-tax';
export const IconRefresh = 'tabler:refresh';
export const IconReload = 'tabler:reload';
export const IconRepeat = 'tabler:repeat';
export const IconReportAnalytics = 'tabler:report-analytics';
export const IconRobot = 'tabler:robot';
export const IconRocket = 'tabler:rocket';
export const IconRoute = 'tabler:route';
export const IconScan = 'tabler:scan';
export const IconScale = 'tabler:scale';
export const IconSchool = 'tabler:school';
export const IconSearch = 'tabler:search';
export const IconSeedling = 'tabler:seedling';
export const IconSend = 'tabler:send';
export const IconSeo = 'tabler:seo';
export const IconServer = 'tabler:server';
export const IconSettings = 'tabler:settings';
export const IconShare = 'tabler:share';
export const IconShield = 'tabler:shield';
export const IconShieldCheck = 'tabler:shield-check';
export const IconShieldLock = 'tabler:shield-lock';
export const IconShoppingCart = 'tabler:shopping-cart';
export const IconSitemap = 'tabler:sitemap';
export const IconSortAscending = 'tabler:sort-ascending';
export const IconSortDescending = 'tabler:sort-descending';
export const IconSpacingVertical = 'tabler:spacing-vertical';
export const IconSparkles = 'tabler:sparkles';
export const IconSpeakerphone = 'tabler:speakerphone';
export const IconSpeedboat = 'tabler:speedboat';
export const IconSquare = 'tabler:square';
export const IconSquareCheck = 'tabler:square-check';
export const IconSquareRounded = 'tabler:square-rounded';
export const IconSquareRoundedCheck = 'tabler:square-rounded-check';
export const IconSquareRoundedCheckFilled = 'tabler:square-rounded-check-filled';
export const IconSquareRoundedMinus = 'tabler:square-rounded-minus';
export const IconSquareRoundedPlus = 'tabler:square-rounded-plus';
export const IconSquareRoundedX = 'tabler:square-rounded-x';
export const IconStack = 'tabler:stack';
export const IconStack2 = 'tabler:stack-2';
export const IconStar = 'tabler:star';
export const IconStarFilled = 'tabler:star-filled';
export const IconStarOff = 'tabler:star-off';
export const IconStrikethrough = 'tabler:strikethrough';
export const IconSubtask = 'tabler:subtask';
export const IconSunHigh = 'tabler:sun-high';
export const IconTable = 'tabler:table';
export const IconTag = 'tabler:tag';
export const IconTags = 'tabler:tags';
export const IconTarget = 'tabler:target';
export const IconTargetArrow = 'tabler:target-arrow';
export const IconTemplate = 'tabler:template';
export const IconTerminal = 'tabler:terminal';
export const IconTestPipe = 'tabler:test-pipe';
export const IconTestPipe2 = 'tabler:test-pipe-2';
export const IconTextCaption = 'tabler:text-caption';
export const IconThumbUp = 'tabler:thumb-up';
export const IconTicket = 'tabler:ticket';
export const IconTimeline = 'tabler:timeline';
export const IconToggleLeft = 'tabler:toggle-left';
export const IconToggleRight = 'tabler:toggle-right';
export const IconTool = 'tabler:tool';
export const IconTools = 'tabler:tools';
export const IconTrash = 'tabler:trash';
export const IconTrendingDown = 'tabler:trending-down';
export const IconTrendingDown2 = 'tabler:trending-down-2';
export const IconTrendingDown3 = 'tabler:trending-down-3';
export const IconTrendingUp = 'tabler:trending-up';
export const IconTrendingUp2 = 'tabler:trending-up-2';
export const IconTrendingUp3 = 'tabler:trending-up-3';
export const IconTrophy = 'tabler:trophy';
export const IconUnderline = 'tabler:underline';
export const IconUpload = 'tabler:upload';
export const IconUser = 'tabler:user';
export const IconUserCheck = 'tabler:user-check';
export const IconUserCircle = 'tabler:user-circle';
export const IconUserEdit = 'tabler:user-edit';
export const IconUserMinus = 'tabler:user-minus';
export const IconUserPlus = 'tabler:user-plus';
export const IconUserOff = 'tabler:user-off';
export const IconUsers = 'tabler:users';
export const IconUsersGroup = 'tabler:users-group';
export const IconBan = 'tabler:ban';
export const IconVideo = 'tabler:video';
export const IconVolume = 'tabler:volume';
export const IconVolumeOff = 'tabler:volume-off';
export const IconWallet = 'tabler:wallet';
export const IconWand = 'tabler:wand';
export const IconWaveSine = 'tabler:wave-sine';
export const IconWebhook = 'tabler:webhook';
export const IconWifi = 'tabler:wifi';
export const IconWorld = 'tabler:world';
export const IconWorldWww = 'tabler:world-www';
export const IconX = 'tabler:x';
export const IconZoomCheck = 'tabler:zoom-check';
export const IconZoomIn = 'tabler:zoom-in';
export const IconZoomMoney = 'tabler:zoom-money';
export const IconZoomOut = 'tabler:zoom-out';

// Aliases
export const IconArrowForward = IconArrowForwardUp;
export const IconBrandTradingview = IconChartCandle;
export const IconChecks = IconChecklist;
export const IconSave = IconDeviceFloppy;

// =============================================================================
// Custom Local SVG Icons (lightweight alternatives)
// =============================================================================

export { default as IconPlusLocal } from './IconPlus.svelte';
export { default as IconXLocal } from './IconX.svelte';
export { default as IconChevronDownLocal } from './IconChevronDown.svelte';
export { default as IconChevronLeftLocal } from './IconChevronLeft.svelte';
export { default as IconChevronRightLocal } from './IconChevronRight.svelte';
export { default as IconCheckLocal } from './IconCheck.svelte';
export { default as IconMinusLocal } from './IconMinus.svelte';
export { default as IconPhotoLocal } from './IconPhoto.svelte';
export { default as IconVideoLocal } from './IconVideo.svelte';
export { default as IconCodeLocal } from './IconCode.svelte';
export { default as IconListLocal } from './IconList.svelte';
export { default as IconPlayerPlayLocal } from './IconPlayerPlay.svelte';
export { default as IconPlayerPauseLocal } from './IconPlayerPause.svelte';
export { default as IconVolumeLocal } from './IconVolume.svelte';
export { default as IconVolumeOffLocal } from './IconVolumeOff.svelte';
export { default as IconMaximizeLocal } from './IconMaximize.svelte';
export { default as IconCopyLocal } from './IconCopy.svelte';
export { default as IconLinkLocal } from './IconLink.svelte';
export { default as IconLayoutGridLocal } from './IconLayoutGrid.svelte';
export { default as IconColumnsLocal } from './IconColumns.svelte';
export { default as IconStarLocal } from './IconStar.svelte';
export { default as IconCircleLocal } from './IconCircle.svelte';
export { default as IconSquareLocal } from './IconSquare.svelte';
export { default as IconSparklesLocal } from './IconSparkles.svelte';

import type { Component } from 'svelte';

/**
 * Type-safe icon component type
 * Use this for props that accept icon components
 */
export type IconComponent = Component<{ size?: number; color?: string; stroke?: number; class?: string }>;
