-- AUTO-GENERATED by docs/audits/G0_3_SCHEMA_BASELINE_2026-05-17.md procedure.
-- Seeds _sqlx_migrations so sqlx::migrate! treats the historical chain as
-- already-applied after schema.sql has been loaded. Fresh envs only.
CREATE TABLE IF NOT EXISTS _sqlx_migrations (
    version        BIGINT PRIMARY KEY,
    description    TEXT        NOT NULL,
    installed_on   TIMESTAMPTZ NOT NULL DEFAULT now(),
    success        BOOLEAN     NOT NULL,
    checksum       BYTEA       NOT NULL,
    execution_time BIGINT      NOT NULL
);
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (0, 'bootstrap_users', true, '\x2e8193dfaec4b609a4395d4cdf56e97a041b788b0597e62b17e53be8e9eec07f68603c24a4f440d117edb09989045319'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (1, 'initial_schema', true, '\x0e5566c82b4f6358177e84c40b0a3a4f4c394d8df28296301a957ae1ff3ee92118f7975e198191205e72693de39fc999'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (2, 'fix_password_column', true, '\x9e50ea0204347d732ec8714b043c434478c9a599b7ed9ae6b31576fc0aaabe539514f8d20ec525218f7e33f91b7fd3d3'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (3, 'fix_jobs_schema', true, '\xa6d78d09446067759ac90aaa7b368f2bdb7afcc017677265e1a4934f2a966ed763f3027f5d5c44dd44d7b5f939e58aae'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (4, 'add_mfa_enabled', true, '\x16eaf3d111f936efa0adc76e5be7eccaf8b51099614a463e1dafe6c237b20139118974c4b5ff5c5e5ba45fd8950b8c9b'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (7, 'email_verification_standalone', true, '\xfe87361092de8d922f9c9374486a47b6f179d79d230d69517bb3e03048c4e4c3e5427ce04050208accb2ad5c75b3eaaf'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (8, 'seed_membership_plans', true, '\x5fd96ebd496a32b2633ec5bf3c6758133d1e91b2ef87010b38dc2b7187f662277f73e14ba563ed636531ad5103bba925'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (9, 'add_performance_indexes', true, '\xfcb2608636fac469a9ca2b009c32a7c74d08745910fb436287d3638d0ae74a536675d9b0f3d9f1196404417577704cbd'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (10, 'fix_coupons_schema', true, '\xadc5bce62d37686eae253168be90780f0e448724fba998f45a9e604749bd73392e9861932269a463d101fd91d12c4d61'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (12, 'add_redirects_table', true, '\x38c2abcb3944deb64bc7ca0963f10702a2cc25a3ae4800e44ba32869d89fd7a43464434467e34a0059ee660baffc6906'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (13, 'trading_room_schedules', true, '\x3e8c44a579185870eb5428e16853719803451933d64b3fcd44be3f269d8303513e09fc5de3e16ae4e10a38e894b7ed64'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (14, 'advanced_cms_features', true, '\x0f1014aabafd9821e26bfca7dbe3049635c95bce2c81d09dbcbe20c668c0540a9efe462d3bb47a45e5a8be97183e7f33'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (15, 'consolidated_schema', true, '\x5e145873fd398426bb7d846ac260e109b20b337253e1ab10c85b46e69ce0ef26bde7a7f62bdc0b28658c5951ca0857ef'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (16, 'fix_course_schema', true, '\x5bcd11d68b3d9e43e309eda4794a11a842d3a236df1fa52b84fd321d8c246f0c65c3005f0f7173026c42b76dc48459b7'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (17, 'fix_schema_mismatches', true, '\xf8cad8d14bfd6a3d9a06786345a37f989dcb7166815f956e09e0cc70a5cb2750af54dd0f24c313078778fcdb4d38cf80'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (18, 'explosive_swings_complete', true, '\x2492802ce77ed88ee3d82fe9f32106c3a8c43ad45962b08fc891cfbf5556832f159e99b5ff4de05a1c8981fce26ef594'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (19, 'subscription_variants', true, '\x7ed50a4582908243c42adea86badf0a5be3701d7280439f83ec81ea243c10b223d7e70d4369631668f69e22a0f1a5de4'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (20, 'add_runner_stop_column', true, '\x9c0647dd8207610e34278e81e10d84ae308d743b0f24fc5e41439bcb1547ecb944cde832b323d95c119137938d65df3a'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (21, 'add_room_slug_to_bunny_uploads', true, '\x921dccf5b63af3721a6f83fbb0dbebfebf0907ab9dc88f014b49753eb3914bfaa2b360c6734530faea50eb4c1c833ccf'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (22, 'position_invalidate_fields', true, '\x4967d5ba1f19d18dbef803f8ebbda1c999c7b47a18282f2a4570163749209226b5ac301ba44735041ecb78b5beec9813'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (23, 'custom_cms_implementation', true, '\xe04b84fc7d2a8f339f0ada7e68673ab5d4e4ff3cc565ecf2e5b1dc6b4d8621a82fa995b87ed28e40353a8aae8a392933'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (24, 'advanced_cms_features', true, '\xa8f018a0b0084e146e439a97174c0e319e34150c829ab9e6e305fb2469d72d3c1f646564b1e61a45c9236189ee159202'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (25, 'blog_editor_enhancements', true, '\x1cc51240a18b4cb73de85859918d5113f9ddd95e8cbcdb8c971baa3c9f7882ae263efd06b37dcbb249bca0c405e4ada1'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (27, 'cms_v2_enterprise_features', true, '\xb2de54a1954a5cec290795fd2282351a87df9266844bbfa825b333d628210135c664fb4c1cdc232d308338714c3862ed'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (28, 'user_favorites_and_stats', true, '\xc66c71dc03993e7c08114de7b18fc6bad8a89a9f240f5f8995f8f0b4069f4e81ed59fcbc92686c05ea69f5db06d8aaf2'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (29, 'cms_reusable_blocks_schema_fix', true, '\xb6ddc5afcecdc0747d57a28050fe6d8053f6b919a7611489c5c6c8948692ea8e3b047d1b04159ad246a4e49eed4c3b02'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (30, 'room_search_indexes', true, '\x5314a8d2ca29a7ea6936434ed4de7f401990acc6b16b62ac7cde0a77912c5bc277c27d95aed7a1a0d9501ff335de1289'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (31, 'analytics_functions', true, '\x6d6251b3836520d644b6fe58ff4eda90b09c20a51906a2bcd1d618d1e2d86efdd12eeae18ed32baff6615e0f2af20c8c'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (32, 'search_function', true, '\x9a1a2c4eb7ecf9373a506665dea54d4cd4439aa06a3360f2571d097d8d101667b561c7be3a0d6d08b875b98aa263391b'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (33, 'oauth_providers', true, '\xd16e1e85546791c48194dc991e9e755b479d09eaa9e11db8d301f8d40cfe9d89aafd02382eb7c64be0af17330b970c25'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (35, 'ict7_member_system_complete', true, '\xe7726f312efe3e1d59a1684532033dd48a17fdbeee85c1cda099c0ac59741605aa38b88d66c009e65bf2a265c79a28f4'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (36, 'room_resources_ict7_complete', true, '\x71988daf5c71ef6b0c2b80f6e4ed4556f201b7d891961ffa4e7de247878d5f9086968d07091a676c9a31052a6b350f4d'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (37, 'forms_ict7_enhancements', true, '\x12f9f7edbb4b4d6066ff1933c228a5788ef942a5df57862570cf6b9705ec6d769dcbb2dfe6110b6ccbf1fba055c63128'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (38, 'popups_system_complete', true, '\x06d51cb62cf81aac18f7e8d3525d1f9ef2a30dce83a683f266bafd26ed26d9013e135ecb933577a1b958525567016f21'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (39, 'resources_ict7_enhanced', true, '\x3ca912343feca8ced1fe72a3f94bc95e20f7b941584b7611984846cab622eb573e42e22b49202e5484779bb4365e122a'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (40, 'courses_ict7_complete', true, '\x52b19efbbb8b96e92dbe650bfce356303f33f895b815fd0751304f10980c069f5483b45ad3cab8b2ea88bfa516daa68b'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (41, 'cms_presets', true, '\xd95ff2ccd84878b1f4dd403c4ef8d0123ecd806c5fc5e19cdc1b94c23ef3ba49d7e6ad5fbd00b1b904de2e0a1511f443'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (42, 'cms_datasources', true, '\x2e53f6f093f2018b669b62e1bdfe463c210375fbb9b84d97f928c44481ec4932167b4a674784a7593e5553a5cc8dee7d'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (43, 'membership_plan_price_history', true, '\x22ca6e5aa44a7cb8cc7ea4161ff03e283690867c5aafb7cd4187350252d7e74b3f723dd578fba86d7601260b0ae67cc9'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (44, 'service_connections', true, '\xf6f190d4801d24beb42b5b3abc7e6d68f643066cf5c84e85bd519ca32e1ddd550b9c5d5aa2d897b9d1e50430bd3929be'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (45, 'blog_post_metadata_and_categories', true, '\xc93b7eb62c34e6dfd68d913f864adad352561d69bb1ec4c260b17477d5930ccd4fe8b714e99eec81448be21106867870'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (50, 'room_fulltext_search_indexes', true, '\xb0855fbb83ecf6210cf50f0dc96297b23d225b6e1e24529f73524ae550a65dc120e87663c16f916fa7e452b08f461229'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (51, 'video_system_ict7_complete', true, '\x6db3ae19f9439ecd28a0ae1404d9ed84e9dd12d73c535248c711d713db7dcd9d8123ae5b4759fc77f68cb9a88d89bc62'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (52, 'crm_deals_pipelines', true, '\xb9e79a62f8e7d9781e7a69c396eb533a2e5e000f898f841f2405853e10f9699e899a12516eb151557d966d1c054b74de'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (53, 'subscription_notifications_ict7', true, '\x88225a2d7bf50d6c359432c65616b1032c4fd6538df9aa791d118c160e8be291bf6a5cf3afce9be52312676354ba4e3f'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (54, 'cms_scheduling_releases', true, '\xd1e9e9b39560061f37de02d5938be504d8035908b6d529fb0cf6a7f54dcbb02b0ae878e549e6c3d4b163a188f9f4f198'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (55, 'webhook_idempotency_and_disputes', true, '\x1d7487176cd111b16da46187770376e331beae0a7ebce070ebf2e59885ef275db8ec566ce5acdacbdc945cab022ea1cc'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (56, 'user_memberships_unique', true, '\x0aaf3b6ac6e6ceceda304431df1ad0fd7bdcb267edba3f764f845556504274eb7d346a1c1983fae88323a0b11eb0c80d'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (57, 'courses_indicators_stripe_price', true, '\x0c35ec12d345bae589677770e8c018d820a628373a744d697c23fb597a1806cf59bc2ca642203ba5683f76035d53356d'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (58, 'reconciliation_log', true, '\x88f43d51d0f88ea86f172b541f57d5653251cf45481ad22a045276229be3efdec5e6a87ac8afa7a71b12876350527c0b'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (59, 'trial_config', true, '\x056dd93ddcd98a6ae940870ad20ae4e912a867b538c544fc6dfa897614dfe915573e9cf70d1461518be2afc602864fec'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (60, 'user_memberships_missing_columns', true, '\x6c401bab075594143abd6e3e548cec7b7a73ffce21ede7bb2d8f5a41d90abfc952acaeaa23e468da1ff87ab4c7e76f59'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (61, 'money_cents_unification', true, '\xbafedcb22601660857e85487f7685d4d150ad0398101557f312ce0611a3d8d4192c37dcf99676124d9a5aead357e36c7'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (62, 'coupons_stripe_mirror', true, '\x70e94b63554d50fae74941c1921ed19cbc3d1fa4dd66fa4c48f1adf1bb0a9ece6edac2e5c8ce4e775b0afafdae255915'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (63, 'user_memberships_partial_unique', true, '\x53451fd5c8f29306c4222c69989bad8370a055b6ed5bfa95eefcb549262fa2a84650e9b63fdae62fd42b838cb191dfbe'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (64, 'email_logs_batch6_columns', true, '\x3bbebcbd8f68cfaec18fbf38067c29d56b1190f5d8548df57b2ba4264996ed31684ed492aed4a88640b7761963703e79'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (65, 'backfill_coupon_usage', true, '\x114f45d9576c6a9255ecabba4809110a1da035cf33c61fba66b6d0a4398862e85500a24c090c75fc2d0a6f1f86bf99a5'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (66, 'drop_unused_oauth_tokens', true, '\xbf70a1a44ea4ac7da9899a3277f60e126a5dc243e14e887bec845bc71c9993d6b48547f91dbba8d7bccaa15d4a259aea'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (67, 'drop_unused_login_rate_limits', true, '\x833f0ef4313b8f5920eb4e6df79113dc6f8ae0762fe7a875b4297fcb494bb5ed236a92e9e8aad6fcedb6be66f871badb'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)
VALUES (68, 'complete_money_cents_bigint', true, '\x9d0a7695dd094c58fd76791afa612905e8c278970f33fae1c2c62ddc39b266855987aa6fabe08d4504d641ad9d2c27b7'::bytea, 0)
ON CONFLICT (version) DO NOTHING;
