/**
 * SEO Email Reports System - Enterprise-Grade Automated Reporting
 * Following SEO Reporting Best Practices (November 2025)
 *
 * Features:
 * - Scheduled automated reports (daily, weekly, monthly)
 * - Customizable report templates
 * - Multiple recipient support
 * - PDF and HTML export formats
 * - Key metrics tracking (rankings, traffic, backlinks)
 * - Competitor comparison reports
 * - Executive summary generation
 * - White-label branding support
 * - Chart and visualization support
 *
 * @version 1.0.0 - November 2025
 */

import { writable, get } from 'svelte/store';
import { browser } from '$app/environment';

// ═══════════════════════════════════════════════════════════════════════════
// Type Definitions
// ═══════════════════════════════════════════════════════════════════════════

export type ReportFrequency = 'daily' | 'weekly' | 'monthly' | 'quarterly';
export type ReportFormat = 'html' | 'pdf' | 'csv';
export type ReportSection =
	| 'executive_summary'
	| 'rankings'
	| 'traffic'
	| 'backlinks'
	| 'technical_issues'
	| 'content_performance'
	| 'competitor_analysis'
	| 'recommendations'
	| 'custom';

export interface ReportRecipient {
	id: string;
	name: string;
	email: string;
	role?: string;
}

export interface ReportMetric {
	name: string;
	value: number | string;
	previousValue?: number | string;
	change?: number;
	changeType?: 'increase' | 'decrease' | 'neutral';
	unit?: string;
	trend?: number[];
}

export interface ReportChart {
	type: 'line' | 'bar' | 'pie' | 'donut' | 'area';
	title: string;
	data: {
		labels: string[];
		datasets: {
			label: string;
			data: number[];
			color?: string;
		}[];
	};
}

export interface ReportSectionConfig {
	id: ReportSection;
	enabled: boolean;
	title: string;
	order: number;
	customContent?: string;
	metrics?: string[];
	charts?: string[];
}

export interface ReportTemplate {
	id: string;
	name: string;
	description?: string;
	frequency: ReportFrequency;
	format: ReportFormat;
	sections: ReportSectionConfig[];
	recipients: ReportRecipient[];
	branding: ReportBranding;
	schedule: ReportSchedule;
	isActive: boolean;
	createdAt: string;
	updatedAt?: string;
}

export interface ReportBranding {
	companyName: string;
	logoUrl?: string;
	primaryColor: string;
	secondaryColor: string;
	headerText?: string;
	footerText?: string;
	customCss?: string;
}

export interface ReportSchedule {
	dayOfWeek?: number; // 0-6 for weekly
	dayOfMonth?: number; // 1-31 for monthly
	hour: number; // 0-23
	minute: number; // 0-59
	timezone: string;
	nextRun?: string;
	lastRun?: string;
}

export interface GeneratedReport {
	id: string;
	templateId: string;
	templateName: string;
	generatedAt: string;
	period: {
		start: string;
		end: string;
	};
	metrics: ReportMetric[];
	sections: {
		id: ReportSection;
		title: string;
		content: string;
		metrics?: ReportMetric[];
		charts?: ReportChart[];
	}[];
	summary: string;
	status: 'draft' | 'sent' | 'failed';
	recipients: string[];
	downloadUrl?: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// Default Configuration
// ═══════════════════════════════════════════════════════════════════════════

export const defaultBranding: ReportBranding = {
	companyName: 'Revolution Trading Pros',
	logoUrl: '/logo.png',
	primaryColor: '#3b82f6',
	secondaryColor: '#1e40af',
	headerText: 'SEO Performance Report',
	footerText: 'Generated by Revolution Trading Pros SEO Suite'
};

export const defaultSections: ReportSectionConfig[] = [
	{
		id: 'executive_summary',
		enabled: true,
		title: 'Executive Summary',
		order: 1,
		metrics: ['overall_score', 'traffic_change', 'ranking_changes']
	},
	{
		id: 'rankings',
		enabled: true,
		title: 'Keyword Rankings',
		order: 2,
		metrics: ['total_keywords', 'top_10_keywords', 'improved_keywords', 'declined_keywords'],
		charts: ['ranking_distribution', 'ranking_trends']
	},
	{
		id: 'traffic',
		enabled: true,
		title: 'Organic Traffic',
		order: 3,
		metrics: ['organic_sessions', 'organic_users', 'bounce_rate', 'avg_session_duration'],
		charts: ['traffic_trend', 'traffic_sources']
	},
	{
		id: 'backlinks',
		enabled: true,
		title: 'Backlink Profile',
		order: 4,
		metrics: ['total_backlinks', 'referring_domains', 'new_backlinks', 'lost_backlinks'],
		charts: ['backlink_trend', 'domain_authority_distribution']
	},
	{
		id: 'technical_issues',
		enabled: true,
		title: 'Technical SEO Issues',
		order: 5,
		metrics: ['critical_issues', 'warnings', 'notices', 'resolved_issues']
	},
	{
		id: 'content_performance',
		enabled: true,
		title: 'Content Performance',
		order: 6,
		metrics: ['top_pages', 'impressions', 'clicks', 'avg_position']
	},
	{
		id: 'competitor_analysis',
		enabled: false,
		title: 'Competitor Analysis',
		order: 7,
		metrics: ['competitor_score', 'market_share', 'keyword_gap']
	},
	{
		id: 'recommendations',
		enabled: true,
		title: 'Recommendations',
		order: 8,
		metrics: ['high_priority', 'medium_priority', 'quick_wins']
	}
];

// ═══════════════════════════════════════════════════════════════════════════
// Report Generation Functions
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Calculate date range based on frequency
 */
export function calculateDateRange(frequency: ReportFrequency): { start: Date; end: Date } {
	const end = new Date();
	const start = new Date();

	switch (frequency) {
		case 'daily':
			start.setDate(end.getDate() - 1);
			break;
		case 'weekly':
			start.setDate(end.getDate() - 7);
			break;
		case 'monthly':
			start.setMonth(end.getMonth() - 1);
			break;
		case 'quarterly':
			start.setMonth(end.getMonth() - 3);
			break;
	}

	return { start, end };
}

/**
 * Calculate percentage change between two values
 */
export function calculateChange(current: number, previous: number): ReportMetric['changeType'] {
	if (current > previous) return 'increase';
	if (current < previous) return 'decrease';
	return 'neutral';
}

/**
 * Format metric value for display
 */
export function formatMetricValue(value: number | string, unit?: string): string {
	if (typeof value === 'string') return value;

	if (unit === 'percent') return `${value.toFixed(1)}%`;
	if (unit === 'currency') return `$${value.toLocaleString()}`;
	if (unit === 'duration') {
		const minutes = Math.floor(value / 60);
		const seconds = Math.floor(value % 60);
		return `${minutes}:${seconds.toString().padStart(2, '0')}`;
	}

	if (value >= 1000000) return `${(value / 1000000).toFixed(1)}M`;
	if (value >= 1000) return `${(value / 1000).toFixed(1)}K`;

	return value.toLocaleString();
}

/**
 * Generate executive summary from metrics
 */
export function generateExecutiveSummary(metrics: ReportMetric[]): string {
	const highlights: string[] = [];
	const concerns: string[] = [];

	for (const metric of metrics) {
		if (metric.change !== undefined) {
			const changeText = `${metric.changeType === 'increase' ? '+' : ''}${metric.change}%`;

			if (metric.changeType === 'increase') {
				highlights.push(`${metric.name} improved by ${changeText}`);
			} else if (metric.changeType === 'decrease' && Math.abs(metric.change) > 5) {
				concerns.push(`${metric.name} decreased by ${Math.abs(metric.change)}%`);
			}
		}
	}

	let summary = '';

	if (highlights.length > 0) {
		summary += `**Key Highlights:**\n${highlights.map((h) => `- ${h}`).join('\n')}\n\n`;
	}

	if (concerns.length > 0) {
		summary += `**Areas of Concern:**\n${concerns.map((c) => `- ${c}`).join('\n')}`;
	}

	return summary || 'Overall performance remains stable with no significant changes.';
}

/**
 * Generate HTML report content
 */
export function generateHtmlReport(
	report: GeneratedReport,
	branding: ReportBranding
): string {
	const sections = report.sections
		.map(
			(section) => `
		<div class="report-section">
			<h2>${section.title}</h2>
			<div class="section-content">
				${section.content}
				${
					section.metrics
						? `
					<div class="metrics-grid">
						${section.metrics
							.map(
								(metric) => `
							<div class="metric-card ${metric.changeType || ''}">
								<div class="metric-name">${metric.name}</div>
								<div class="metric-value">${formatMetricValue(metric.value, metric.unit)}</div>
								${
									metric.change !== undefined
										? `
									<div class="metric-change">
										${metric.change > 0 ? '↑' : metric.change < 0 ? '↓' : '→'}
										${Math.abs(metric.change)}%
									</div>
								`
										: ''
								}
							</div>
						`
							)
							.join('')}
					</div>
				`
						: ''
				}
			</div>
		</div>
	`
		)
		.join('');

	return `
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>${branding.headerText || 'SEO Report'}</title>
	<style>
		:root {
			--primary-color: ${branding.primaryColor};
			--secondary-color: ${branding.secondaryColor};
		}

		body {
			font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
			line-height: 1.6;
			color: #333;
			max-width: 900px;
			margin: 0 auto;
			padding: 2rem;
		}

		.report-header {
			text-align: center;
			padding: 2rem;
			background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
			color: white;
			border-radius: 12px;
			margin-bottom: 2rem;
		}

		.report-header img {
			max-height: 60px;
			margin-bottom: 1rem;
		}

		.report-header h1 {
			margin: 0;
			font-size: 1.75rem;
		}

		.report-period {
			opacity: 0.9;
			font-size: 0.9rem;
		}

		.report-section {
			background: white;
			border: 1px solid #e5e7eb;
			border-radius: 8px;
			padding: 1.5rem;
			margin-bottom: 1.5rem;
		}

		.report-section h2 {
			color: var(--primary-color);
			margin-top: 0;
			padding-bottom: 0.5rem;
			border-bottom: 2px solid var(--primary-color);
		}

		.metrics-grid {
			display: grid;
			grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
			gap: 1rem;
			margin-top: 1rem;
		}

		.metric-card {
			background: #f9fafb;
			padding: 1rem;
			border-radius: 6px;
			text-align: center;
		}

		.metric-card.increase { border-left: 4px solid #10b981; }
		.metric-card.decrease { border-left: 4px solid #ef4444; }
		.metric-card.neutral { border-left: 4px solid #6b7280; }

		.metric-name {
			font-size: 0.85rem;
			color: #666;
			margin-bottom: 0.25rem;
		}

		.metric-value {
			font-size: 1.5rem;
			font-weight: 700;
			color: #1a1a1a;
		}

		.metric-change {
			font-size: 0.85rem;
			margin-top: 0.25rem;
		}

		.metric-card.increase .metric-change { color: #10b981; }
		.metric-card.decrease .metric-change { color: #ef4444; }

		.report-footer {
			text-align: center;
			padding: 2rem;
			color: #666;
			font-size: 0.85rem;
			border-top: 1px solid #e5e7eb;
			margin-top: 2rem;
		}

		${branding.customCss || ''}
	</style>
</head>
<body>
	<div class="report-header">
		${branding.logoUrl ? `<img src="${branding.logoUrl}" alt="${branding.companyName}">` : ''}
		<h1>${branding.headerText || 'SEO Performance Report'}</h1>
		<div class="report-period">
			${new Date(report.period.start).toLocaleDateString()} - ${new Date(report.period.end).toLocaleDateString()}
		</div>
	</div>

	${sections}

	<div class="report-footer">
		<p>${branding.footerText || 'Generated automatically'}</p>
		<p>Report generated: ${new Date(report.generatedAt).toLocaleString()}</p>
	</div>
</body>
</html>
	`;
}

/**
 * Generate CSV report content
 */
export function generateCsvReport(report: GeneratedReport): string {
	const rows: string[][] = [];

	// Header
	rows.push(['Metric', 'Value', 'Previous Value', 'Change', 'Change Type']);

	// Metrics
	for (const metric of report.metrics) {
		rows.push([
			metric.name,
			String(metric.value),
			String(metric.previousValue || ''),
			metric.change !== undefined ? `${metric.change}%` : '',
			metric.changeType || ''
		]);
	}

	return rows.map((row) => row.map((cell) => `"${cell}"`).join(',')).join('\n');
}

// ═══════════════════════════════════════════════════════════════════════════
// Schedule Management
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Calculate next run date based on schedule
 */
export function calculateNextRun(schedule: ReportSchedule, frequency: ReportFrequency): Date {
	const now = new Date();
	const next = new Date();

	// Set time
	next.setHours(schedule.hour, schedule.minute, 0, 0);

	switch (frequency) {
		case 'daily':
			if (next <= now) {
				next.setDate(next.getDate() + 1);
			}
			break;

		case 'weekly':
			const dayDiff = (schedule.dayOfWeek || 0) - now.getDay();
			next.setDate(now.getDate() + (dayDiff <= 0 ? dayDiff + 7 : dayDiff));
			if (next <= now) {
				next.setDate(next.getDate() + 7);
			}
			break;

		case 'monthly':
			next.setDate(schedule.dayOfMonth || 1);
			if (next <= now) {
				next.setMonth(next.getMonth() + 1);
			}
			break;

		case 'quarterly':
			next.setDate(schedule.dayOfMonth || 1);
			const quarterMonth = Math.floor(now.getMonth() / 3) * 3;
			next.setMonth(quarterMonth);
			if (next <= now) {
				next.setMonth(next.getMonth() + 3);
			}
			break;
	}

	return next;
}

/**
 * Format schedule for display
 */
export function formatSchedule(schedule: ReportSchedule, frequency: ReportFrequency): string {
	const time = `${schedule.hour.toString().padStart(2, '0')}:${schedule.minute.toString().padStart(2, '0')}`;
	const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

	switch (frequency) {
		case 'daily':
			return `Daily at ${time}`;
		case 'weekly':
			return `Every ${days[schedule.dayOfWeek || 0]} at ${time}`;
		case 'monthly':
			return `Monthly on day ${schedule.dayOfMonth || 1} at ${time}`;
		case 'quarterly':
			return `Quarterly on day ${schedule.dayOfMonth || 1} at ${time}`;
		default:
			return time;
	}
}

// ═══════════════════════════════════════════════════════════════════════════
// Svelte Store
// ═══════════════════════════════════════════════════════════════════════════

const STORAGE_KEY = 'seo-report-templates';

function createReportStore() {
	let initial: ReportTemplate[] = [];

	if (browser) {
		const stored = localStorage.getItem(STORAGE_KEY);
		if (stored) {
			try {
				initial = JSON.parse(stored);
			} catch {
				// Use empty array on parse error
			}
		}
	}

	const { subscribe, set, update } = writable<ReportTemplate[]>(initial);

	const save = (templates: ReportTemplate[]) => {
		if (browser) {
			localStorage.setItem(STORAGE_KEY, JSON.stringify(templates));
		}
	};

	return {
		subscribe,

		add: (template: Omit<ReportTemplate, 'id' | 'createdAt'>) => {
			const newTemplate: ReportTemplate = {
				...template,
				id: crypto.randomUUID(),
				createdAt: new Date().toISOString()
			};

			update((templates) => {
				const updated = [...templates, newTemplate];
				save(updated);
				return updated;
			});

			return newTemplate;
		},

		update: (id: string, data: Partial<ReportTemplate>) => {
			update((templates) => {
				const updated = templates.map((t) =>
					t.id === id ? { ...t, ...data, updatedAt: new Date().toISOString() } : t
				);
				save(updated);
				return updated;
			});
		},

		remove: (id: string) => {
			update((templates) => {
				const updated = templates.filter((t) => t.id !== id);
				save(updated);
				return updated;
			});
		},

		toggle: (id: string) => {
			update((templates) => {
				const updated = templates.map((t) =>
					t.id === id
						? { ...t, isActive: !t.isActive, updatedAt: new Date().toISOString() }
						: t
				);
				save(updated);
				return updated;
			});
		},

		get: (id: string) => {
			const templates = get({ subscribe });
			return templates.find((t) => t.id === id);
		}
	};
}

export const reportTemplates = createReportStore();

// Generated reports store
export const generatedReports = writable<GeneratedReport[]>([]);

// ═══════════════════════════════════════════════════════════════════════════
// Export Default
// ═══════════════════════════════════════════════════════════════════════════

export default {
	calculateDateRange,
	calculateChange,
	formatMetricValue,
	generateExecutiveSummary,
	generateHtmlReport,
	generateCsvReport,
	calculateNextRun,
	formatSchedule,
	templates: reportTemplates,
	reports: generatedReports,
	defaultBranding,
	defaultSections
};
