<!--
	Account Dashboard - User Profile & Settings
	Matches WordPress Simpler Trading reference implementation

	Features:
	- Profile Information (name, email, avatar)
	- Change Password
	- Memberships display (active/expired)
	- Billing Information

	@version 1.0.0
	@author Revolution Trading Pros

	Svelte 5 Features:
	- $props() for page data
	- $state() for form state
	- $derived() for computed values
	- use:enhance for progressive form enhancement
-->
<script lang="ts">
	import { enhance } from '$app/forms';
	// SvelteKit auto-generates types - this import will be available after build
	// @ts-expect-error - $types is generated by SvelteKit during build
	import type { ActionData, PageData } from './$types';

	interface Props {
		data: PageData;
		form: ActionData;
	}

	let { data, form }: Props = $props();

	// Form submission state
	let isSubmittingProfile = $state(false);
	let isSubmittingPassword = $state(false);

	// Derived user name from data
	let displayName = $derived(data.user?.name || 'Member');
	let userEmail = $derived(data.user?.email || '');
	let firstName = $derived(displayName.split(' ')[0] || '');
	let lastName = $derived(displayName.split(' ').slice(1).join(' ') || '');

	// Generate avatar URL (Gravatar or placeholder)
	let avatarUrl = $derived.by(() => {
		if (data.user?.avatar) return data.user.avatar;
		// Generate placeholder with initials
		const initials = `${firstName.charAt(0)}${lastName.charAt(0) || firstName.charAt(1) || ''}`.toUpperCase();
		return `https://ui-avatars.com/api/?name=${encodeURIComponent(initials)}&background=1a73e8&color=fff&size=100`;
	});
</script>

<svelte:head>
	<title>My Account | Revolution Trading Pros</title>
</svelte:head>

<div class="account-page">
	<!-- Page Header -->
	<header class="account-header">
		<h1>My Account</h1>
	</header>

	<!-- Main Content -->
	<div class="account-content">
		<!-- Success/Error Messages -->
		{#if form?.success}
			<div class="alert alert-success">
				{form.message}
			</div>
		{/if}

		{#if form?.error}
			<div class="alert alert-error">
				{form.error}
			</div>
		{/if}

		<div class="account-sections">
			<!-- ═══════════════════════════════════════════════════════════════════
			     Profile Information Section
			     ═══════════════════════════════════════════════════════════════════ -->
			<section class="account-section">
				<h2>Profile Information</h2>

				<form
					method="POST"
					action="?/updateProfile"
					use:enhance={() => {
						isSubmittingProfile = true;
						return async ({ update }) => {
							await update();
							isSubmittingProfile = false;
						};
					}}
				>
					<div class="form-row">
						<div class="form-group">
							<label for="first_name" class="block text-sm font-medium text-gray-700">
								First Name
							</label>
							<input
								type="text"
								id="first_name"
								name="first_name"
								value={firstName}
								required
							/>
						</div>

						<div class="form-group">
							<label for="last_name" class="block text-sm font-medium text-gray-700">
								Last Name
							</label>
							<input
								type="text"
								id="last_name"
								name="last_name"
								value={lastName}
								required
							/>
						</div>
					</div>

					<div class="form-group">
						<label for="email" class="block text-sm font-medium text-gray-700">
							Email Address
						</label>
						<input
							type="email"
							id="email"
							name="email"
							value={userEmail}
							required
						/>
					</div>

					<div class="form-group">
						<label for="profile-photo-display">Profile Photo</label>
						<div id="profile-photo-display" class="profile-photo">
							<img src={avatarUrl} alt={displayName} class="avatar" />
							<p class="photo-help">
								Profile photo managed through Gravatar.
								<a href="https://en.gravatar.com/" target="_blank" rel="noopener noreferrer">
									Change on Gravatar
								</a>
							</p>
						</div>
					</div>

					<div class="form-actions">
						<button type="submit" class="btn btn-primary" disabled={isSubmittingProfile}>
							{isSubmittingProfile ? 'Updating...' : 'Update Profile'}
						</button>
					</div>
				</form>
			</section>

			<!-- ═══════════════════════════════════════════════════════════════════
			     Change Password Section
			     ═══════════════════════════════════════════════════════════════════ -->
			<section class="account-section">
				<h2>Change Password</h2>

				<form
					method="POST"
					action="?/updatePassword"
					use:enhance={() => {
						isSubmittingPassword = true;
						return async ({ update, result }) => {
							await update();
							isSubmittingPassword = false;
							// Clear password fields on success
							if (result.type === 'success') {
								const form = document.querySelector('.password-form') as HTMLFormElement;
								form?.reset();
							}
						};
					}}
					class="password-form"
				>
					<div class="form-group">
						<label for="current_password">Current Password</label>
						<input
							type="password"
							id="current_password"
							name="current_password"
							required
							autocomplete="current-password"
						/>
					</div>

					<div class="form-row">
						<div class="form-group">
							<label for="new_password">New Password</label>
							<input
								type="password"
								id="new_password"
								name="new_password"
								required
								minlength="8"
								autocomplete="new-password"
							/>
							<small class="form-help">Minimum 8 characters</small>
						</div>

						<div class="form-group">
							<label for="confirm_password">Confirm New Password</label>
							<input
								type="password"
								id="confirm_password"
								name="confirm_password"
								required
								minlength="8"
								autocomplete="new-password"
							/>
						</div>
					</div>

					<div class="form-actions">
						<button type="submit" class="btn btn-primary" disabled={isSubmittingPassword}>
							{isSubmittingPassword ? 'Changing...' : 'Change Password'}
						</button>
					</div>
				</form>
			</section>

			<!-- ═══════════════════════════════════════════════════════════════════
			     Memberships Section
			     ═══════════════════════════════════════════════════════════════════ -->
			<section class="account-section">
				<h2>Memberships</h2>

				<div class="memberships-list">
					{#if data.memberships && data.memberships.active && data.memberships.active.length > 0}
						<h3>Active Memberships</h3>
						{#each data.memberships.active as membership}
							<div class="membership-item active">
								<h4>{membership.name}</h4>
								<p>Status: <span class="status-active">Active</span></p>
								<p>Started: {membership.startDate}</p>
								{#if membership.endDate}
									<p>Expires: {membership.endDate}</p>
								{/if}
								<div class="membership-actions">
									<a href="/dashboard/{membership.slug}" class="btn btn-secondary">
										View Dashboard
									</a>
								</div>
							</div>
						{/each}
					{:else}
						<div class="empty-state">
							<p>No active memberships</p>
							<a href="/memberships" class="btn btn-primary">Browse Memberships</a>
						</div>
					{/if}

					{#if data.memberships && data.memberships.expired && data.memberships.expired.length > 0}
						<h3>Expired Memberships</h3>
						{#each data.memberships.expired as membership}
							<div class="membership-item expired">
								<h4>{membership.name}</h4>
								<p>Status: <span class="status-expired">Expired</span></p>
								<p>Expired: {membership.endDate}</p>
								<div class="membership-actions">
									<a href="/renew/{membership.slug}" class="btn btn-primary">
										Renew
									</a>
								</div>
							</div>
						{/each}
					{/if}
				</div>
			</section>

			<!-- ═══════════════════════════════════════════════════════════════════
			     Billing Information Section
			     ═══════════════════════════════════════════════════════════════════ -->
			<section class="account-section">
				<h2>Billing Information</h2>

				<div class="billing-info">
					{#if data.billing?.email}
						<div class="billing-item">
							<span class="billing-label">Billing Email:</span>
							<span>{data.billing.email}</span>
						</div>
					{/if}

					{#if data.billing?.phone}
						<div class="billing-item">
							<span class="billing-label">Phone:</span>
							<span>{data.billing.phone}</span>
						</div>
					{/if}

					{#if data.billing?.address}
						<div class="billing-item">
							<span class="billing-label">Billing Address:</span>
							<address>{@html data.billing.address}</address>
						</div>
					{:else}
						<p class="empty-text">No billing address on file</p>
					{/if}

					<div class="billing-actions">
						<a href="/dashboard/account/billing" class="btn btn-secondary">
							Edit Billing Address
						</a>
						<a href="/dashboard/account/orders" class="btn btn-secondary">
							View Order History
						</a>
					</div>
				</div>
			</section>
		</div>
	</div>
</div>

<style>
	/* ═══════════════════════════════════════════════════════════════════════════
	 * Account Page Container
	 * ═══════════════════════════════════════════════════════════════════════════ */

	.account-page {
		padding: 0;
	}

	/* ═══════════════════════════════════════════════════════════════════════════
	 * Page Header
	 * ═══════════════════════════════════════════════════════════════════════════ */

	.account-header {
		background: #fff;
		padding: 24px 32px;
		border-bottom: 1px solid #e0e0e0;
	}

	.account-header h1 {
		margin: 0;
		font-size: 24px;
		font-weight: 600;
		color: #333;
		font-family: 'Open Sans', sans-serif;
	}

	/* ═══════════════════════════════════════════════════════════════════════════
	 * Main Content Area
	 * ═══════════════════════════════════════════════════════════════════════════ */

	.account-content {
		padding: 32px;
	}

	.account-sections {
		display: grid;
		gap: 24px;
	}

	/* ═══════════════════════════════════════════════════════════════════════════
	 * Section Cards
	 * ═══════════════════════════════════════════════════════════════════════════ */

	.account-section {
		background: #fff;
		padding: 32px;
		border-radius: 8px;
		border: 1px solid #e0e0e0;
	}

	.account-section h2 {
		margin: 0 0 24px 0;
		font-size: 18px;
		font-weight: 600;
		color: #333;
		font-family: 'Open Sans', sans-serif;
	}

	.account-section h3 {
		margin: 0 0 16px 0;
		font-size: 14px;
		font-weight: 600;
		color: #666;
		text-transform: uppercase;
		letter-spacing: 0.5px;
	}

	/* ═══════════════════════════════════════════════════════════════════════════
	 * Form Styles
	 * ═══════════════════════════════════════════════════════════════════════════ */

	.form-row {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 20px;
	}

	.form-group {
		margin-bottom: 20px;
	}

	.form-group label {
		display: block;
		margin-bottom: 8px;
		font-weight: 600;
		font-size: 14px;
		color: #555;
	}

	.form-group input {
		width: 100%;
		padding: 12px 16px;
		border: 1px solid #ddd;
		border-radius: 4px;
		font-size: 14px;
		font-family: 'Open Sans', sans-serif;
		transition: border-color 0.2s ease, box-shadow 0.2s ease;
	}

	.form-group input:focus {
		outline: none;
		border-color: #1a73e8;
		box-shadow: 0 0 0 3px rgba(26, 115, 232, 0.1);
	}

	.form-help {
		display: block;
		margin-top: 6px;
		font-size: 12px;
		color: #888;
	}

	.form-actions {
		margin-top: 24px;
		padding-top: 24px;
		border-top: 1px solid #eee;
	}

	/* ═══════════════════════════════════════════════════════════════════════════
	 * Profile Photo
	 * ═══════════════════════════════════════════════════════════════════════════ */

	.profile-photo {
		display: flex;
		align-items: center;
		gap: 20px;
	}

	.avatar {
		width: 100px;
		height: 100px;
		border-radius: 50%;
		border: 3px solid #1a73e8;
		object-fit: cover;
	}

	.photo-help {
		font-size: 14px;
		color: #666;
		margin: 0;
	}

	.photo-help a {
		color: #1a73e8;
		text-decoration: none;
	}

	.photo-help a:hover {
		text-decoration: underline;
	}

	/* ═══════════════════════════════════════════════════════════════════════════
	 * Buttons
	 * ═══════════════════════════════════════════════════════════════════════════ */

	.btn {
		display: inline-block;
		padding: 12px 24px;
		font-size: 14px;
		font-weight: 600;
		font-family: 'Open Sans', sans-serif;
		border-radius: 4px;
		cursor: pointer;
		text-decoration: none;
		transition: all 0.2s ease;
	}

	.btn-primary {
		background: #1a73e8;
		color: #fff;
		border: none;
	}

	.btn-primary:hover:not(:disabled) {
		background: #1557b0;
	}

	.btn-primary:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.btn-secondary {
		background: #fff;
		color: #333;
		border: 1px solid #ddd;
	}

	.btn-secondary:hover {
		background: #f5f5f5;
		border-color: #ccc;
	}

	/* ═══════════════════════════════════════════════════════════════════════════
	 * Alerts
	 * ═══════════════════════════════════════════════════════════════════════════ */

	.alert {
		padding: 16px 20px;
		border-radius: 4px;
		margin-bottom: 24px;
		font-size: 14px;
	}

	.alert-success {
		background: #d4edda;
		color: #155724;
		border: 1px solid #c3e6cb;
	}

	.alert-error {
		background: #f8d7da;
		color: #721c24;
		border: 1px solid #f5c6cb;
	}

	/* ═══════════════════════════════════════════════════════════════════════════
	 * Memberships
	 * ═══════════════════════════════════════════════════════════════════════════ */

	.memberships-list {
		display: grid;
		gap: 16px;
	}

	.membership-item {
		padding: 20px;
		border: 1px solid #ddd;
		border-radius: 8px;
	}

	.membership-item h4 {
		margin: 0 0 12px 0;
		font-size: 16px;
		font-weight: 600;
		color: #333;
	}

	.membership-item p {
		margin: 0 0 8px 0;
		font-size: 14px;
		color: #666;
	}

	.membership-item.active {
		border-color: #28a745;
		background: #f8fff9;
	}

	.membership-item.expired {
		border-color: #dc3545;
		background: #fff8f8;
	}

	.status-active {
		color: #28a745;
		font-weight: 600;
	}

	.status-expired {
		color: #dc3545;
		font-weight: 600;
	}

	.membership-actions {
		margin-top: 16px;
	}

	.empty-state {
		text-align: center;
		padding: 32px;
		background: #f9f9f9;
		border-radius: 8px;
	}

	.empty-state p {
		margin: 0 0 16px 0;
		color: #666;
	}

	/* ═══════════════════════════════════════════════════════════════════════════
	 * Billing Information
	 * ═══════════════════════════════════════════════════════════════════════════ */

	.billing-info {
		display: grid;
		gap: 16px;
	}

	.billing-item {
		display: flex;
		gap: 16px;
	}

	.billing-item .billing-label {
		font-weight: 600;
		color: #555;
		min-width: 120px;
	}

	.billing-item span,
	.billing-item address {
		color: #333;
		font-style: normal;
	}

	.billing-actions {
		display: flex;
		gap: 12px;
		margin-top: 24px;
		padding-top: 24px;
		border-top: 1px solid #eee;
	}

	.empty-text {
		color: #888;
		font-style: italic;
	}

	/* ═══════════════════════════════════════════════════════════════════════════
	 * Responsive - Mobile (≤768px)
	 * ═══════════════════════════════════════════════════════════════════════════ */

	@media (max-width: 768px) {
		.account-header {
			padding: 20px;
		}

		.account-content {
			padding: 20px;
		}

		.account-section {
			padding: 20px;
		}

		.form-row {
			grid-template-columns: 1fr;
		}

		.profile-photo {
			flex-direction: column;
			text-align: center;
		}

		.billing-item {
			flex-direction: column;
			gap: 4px;
		}

		.billing-actions {
			flex-direction: column;
		}

		.billing-actions .btn {
			width: 100%;
			text-align: center;
		}
	}

	/* ═══════════════════════════════════════════════════════════════════════════
	 * Reduced Motion
	 * ═══════════════════════════════════════════════════════════════════════════ */

	@media (prefers-reduced-motion: reduce) {
		.form-group input,
		.btn {
			transition: none;
		}
	}
</style>
