<!--
	CMS v2 SEO Settings Page
	═══════════════════════════════════════════════════════════════════════════════

	Comprehensive SEO management including:
	- Global SEO defaults
	- Structured data templates (JSON-LD)
	- Sitemap configuration
	- Robots.txt editor
	- Open Graph defaults
	- Analytics integration

	@version 1.0.0
	@author Revolution Trading Pros
	@since January 2026
-->

<script lang="ts">
	import { browser } from '$app/environment';
	import { fly, scale } from 'svelte/transition';
	import {
		IconSearch,
		IconWorld,
		IconCode,
		IconFile,
		IconDeviceFloppy,
		IconRefresh,
		IconCheck,
		IconAlertTriangle,
		IconChartLine,
		IconBrandGoogle,
		IconBrandTwitter,
		IconBrandFacebook,
		IconSettings
	} from '$lib/icons';

	// ═══════════════════════════════════════════════════════════════════════════
	// Types
	// ═══════════════════════════════════════════════════════════════════════════

	interface SeoSettings {
		siteName: string;
		siteDescription: string;
		defaultTitle: string;
		titleSeparator: string;
		defaultMetaDescription: string;
		defaultOgImage: string;
		twitterHandle: string;
		facebookAppId: string;
		googleSiteVerification: string;
		bingSiteVerification: string;
		robotsDefault: string;
		sitemapEnabled: boolean;
		sitemapChangeFreq: string;
		sitemapPriority: number;
	}

	interface StructuredDataTemplate {
		id: string;
		name: string;
		type: string;
		template: Record<string, unknown>;
		isActive: boolean;
	}

	// ═══════════════════════════════════════════════════════════════════════════
	// State
	// ═══════════════════════════════════════════════════════════════════════════

	let activeTab = $state<'general' | 'structured' | 'sitemap' | 'robots' | 'social'>('general');
	let isSaving = $state(false);
	let successMessage = $state<string | null>(null);
	let error = $state<string | null>(null);

	// SEO Settings
	let settings = $state<SeoSettings>({
		siteName: 'Revolution Trading Pros',
		siteDescription: 'Professional trading education, indicators, and alert services',
		defaultTitle: 'Revolution Trading Pros - Trading Education & Tools',
		titleSeparator: '|',
		defaultMetaDescription:
			'Join 18,000+ traders learning professional trading strategies. Access live trading rooms, custom indicators, and expert-led courses.',
		defaultOgImage: '/images/og-default.jpg',
		twitterHandle: '@RevTradingPros',
		facebookAppId: '',
		googleSiteVerification: '',
		bingSiteVerification: '',
		robotsDefault: 'index, follow',
		sitemapEnabled: true,
		sitemapChangeFreq: 'weekly',
		sitemapPriority: 0.8
	});

	// Robots.txt content
	let robotsTxt = $state(`# Revolution Trading Pros Robots.txt
# Generated by CMS v2

User-agent: *
Allow: /

# Disallow admin areas
Disallow: /admin/
Disallow: /api/

# Sitemap
Sitemap: https://revolutiontradingpros.com/sitemap.xml
`);

	// Structured data templates
	let structuredDataTemplates = $state<StructuredDataTemplate[]>([
		{
			id: '1',
			name: 'Organization',
			type: 'Organization',
			template: {
				'@context': 'https://schema.org',
				'@type': 'Organization',
				name: 'Revolution Trading Pros',
				url: 'https://revolutiontradingpros.com',
				logo: 'https://revolutiontradingpros.com/logo.png',
				contactPoint: {
					'@type': 'ContactPoint',
					telephone: '',
					contactType: 'customer service'
				},
				sameAs: ['https://twitter.com/RevTradingPros', 'https://facebook.com/RevTradingPros']
			},
			isActive: true
		},
		{
			id: '2',
			name: 'Website',
			type: 'WebSite',
			template: {
				'@context': 'https://schema.org',
				'@type': 'WebSite',
				name: 'Revolution Trading Pros',
				url: 'https://revolutiontradingpros.com',
				potentialAction: {
					'@type': 'SearchAction',
					target: 'https://revolutiontradingpros.com/search?q={search_term_string}',
					'query-input': 'required name=search_term_string'
				}
			},
			isActive: true
		},
		{
			id: '3',
			name: 'Course Template',
			type: 'Course',
			template: {
				'@context': 'https://schema.org',
				'@type': 'Course',
				name: '{{title}}',
				description: '{{description}}',
				provider: {
					'@type': 'Organization',
					name: 'Revolution Trading Pros'
				},
				courseMode: 'online',
				hasCourseInstance: {
					'@type': 'CourseInstance',
					courseMode: 'online'
				}
			},
			isActive: true
		},
		{
			id: '4',
			name: 'Product Template',
			type: 'Product',
			template: {
				'@context': 'https://schema.org',
				'@type': 'Product',
				name: '{{title}}',
				description: '{{description}}',
				brand: {
					'@type': 'Brand',
					name: 'Revolution Trading Pros'
				},
				offers: {
					'@type': 'Offer',
					price: '{{price}}',
					priceCurrency: 'USD',
					availability: 'https://schema.org/InStock'
				}
			},
			isActive: true
		}
	]);

	let editingTemplate = $state<StructuredDataTemplate | null>(null);
	let templateJson = $state('');

	// Sitemap settings
	let sitemapExcludedPaths = $state<string[]>([
		'/admin/*',
		'/api/*',
		'/auth/*',
		'/checkout/*',
		'/*.json'
	]);

	// ═══════════════════════════════════════════════════════════════════════════
	// Actions
	// ═══════════════════════════════════════════════════════════════════════════

	async function saveSettings() {
		isSaving = true;
		error = null;
		successMessage = null;

		try {
			// Simulate API call
			await new Promise((resolve) => setTimeout(resolve, 500));
			successMessage = 'Settings saved successfully';
			setTimeout(() => (successMessage = null), 3000);
		} catch (e: any) {
			error = e.message || 'Failed to save settings';
		} finally {
			isSaving = false;
		}
	}

	async function regenerateSitemap() {
		isSaving = true;
		error = null;

		try {
			// Simulate API call
			await new Promise((resolve) => setTimeout(resolve, 1000));
			successMessage = 'Sitemap regenerated successfully';
			setTimeout(() => (successMessage = null), 3000);
		} catch (e: any) {
			error = e.message || 'Failed to regenerate sitemap';
		} finally {
			isSaving = false;
		}
	}

	function editTemplate(template: StructuredDataTemplate) {
		editingTemplate = template;
		templateJson = JSON.stringify(template.template, null, 2);
	}

	function saveTemplate() {
		if (!editingTemplate) return;

		try {
			const parsed = JSON.parse(templateJson);
			const index = structuredDataTemplates.findIndex((t) => t.id === editingTemplate!.id);
			if (index !== -1) {
				structuredDataTemplates[index] = {
					...structuredDataTemplates[index],
					template: parsed
				};
			}
			editingTemplate = null;
			templateJson = '';
			successMessage = 'Template updated successfully';
			setTimeout(() => (successMessage = null), 3000);
		} catch (e) {
			error = 'Invalid JSON syntax';
		}
	}

	function toggleTemplate(id: string) {
		const index = structuredDataTemplates.findIndex((t) => t.id === id);
		if (index !== -1) {
			structuredDataTemplates[index].isActive = !structuredDataTemplates[index].isActive;
		}
	}

	function addExcludedPath() {
		const path = prompt('Enter path pattern to exclude (e.g., /private/*)');
		if (path && !sitemapExcludedPaths.includes(path)) {
			sitemapExcludedPaths = [...sitemapExcludedPaths, path];
		}
	}

	function removeExcludedPath(path: string) {
		sitemapExcludedPaths = sitemapExcludedPaths.filter((p) => p !== path);
	}
</script>

<svelte:head>
	<title>SEO Settings | CMS v2</title>
</svelte:head>

<div class="seo-page">
	<!-- Header -->
	<header class="page-header" in:fly={{ y: -20, duration: 300 }}>
		<div class="header-content">
			<IconSearch size={24} class="header-icon" />
			<div>
				<h1 class="page-title">SEO Settings</h1>
				<p class="page-subtitle">Optimize your site for search engines</p>
			</div>
		</div>

		<div class="header-actions">
			<button class="btn-primary" onclick={saveSettings} disabled={isSaving}>
				<IconDeviceFloppy size={18} />
				{isSaving ? 'Saving...' : 'Save All Settings'}
			</button>
		</div>
	</header>

	{#if successMessage}
		<div class="success-banner" in:scale={{ duration: 200 }}>
			<IconCheck size={18} />
			<span>{successMessage}</span>
		</div>
	{/if}

	{#if error}
		<div class="error-banner" in:scale={{ duration: 200 }}>
			<IconAlertTriangle size={18} />
			<span>{error}</span>
			<button onclick={() => (error = null)}>Dismiss</button>
		</div>
	{/if}

	<!-- Tabs -->
	<div class="tabs" in:fly={{ y: 20, duration: 300, delay: 50 }}>
		<button
			class="tab-btn"
			class:active={activeTab === 'general'}
			onclick={() => (activeTab = 'general')}
		>
			<IconSettings size={16} />
			General
		</button>
		<button
			class="tab-btn"
			class:active={activeTab === 'structured'}
			onclick={() => (activeTab = 'structured')}
		>
			<IconCode size={16} />
			Structured Data
		</button>
		<button
			class="tab-btn"
			class:active={activeTab === 'sitemap'}
			onclick={() => (activeTab = 'sitemap')}
		>
			<IconWorld size={16} />
			Sitemap
		</button>
		<button
			class="tab-btn"
			class:active={activeTab === 'robots'}
			onclick={() => (activeTab = 'robots')}
		>
			<IconFile size={16} />
			Robots.txt
		</button>
		<button
			class="tab-btn"
			class:active={activeTab === 'social'}
			onclick={() => (activeTab = 'social')}
		>
			<IconBrandFacebook size={16} />
			Social
		</button>
	</div>

	<!-- Tab Content -->
	<div class="tab-content" in:fly={{ y: 20, duration: 300, delay: 100 }}>
		<!-- General Tab -->
		{#if activeTab === 'general'}
			<div class="settings-grid">
				<div class="settings-card">
					<h2 class="card-title">Site Information</h2>

					<div class="field-group">
						<label for="site-name" class="field-label">Site Name</label>
						<input
							id="site-name"
							type="text"
							bind:value={settings.siteName}
							class="field-input"
							placeholder="Your Site Name"
						/>
					</div>

					<div class="field-group">
						<label for="site-desc" class="field-label">Site Description</label>
						<textarea
							id="site-desc"
							bind:value={settings.siteDescription}
							class="field-textarea"
							rows="2"
							placeholder="Brief description of your site"
						></textarea>
					</div>

					<div class="field-group">
						<label for="default-title" class="field-label">Default Title</label>
						<input
							id="default-title"
							type="text"
							bind:value={settings.defaultTitle}
							class="field-input"
							placeholder="Default page title"
						/>
					</div>

					<div class="field-row">
						<div class="field-group">
							<label for="title-sep" class="field-label">Title Separator</label>
							<select id="title-sep" bind:value={settings.titleSeparator} class="field-select">
								<option value="|">| (Pipe)</option>
								<option value="-">- (Dash)</option>
								<option value="·">· (Middle Dot)</option>
								<option value="»">» (Chevron)</option>
							</select>
						</div>
					</div>
				</div>

				<div class="settings-card">
					<h2 class="card-title">Default Meta Tags</h2>

					<div class="field-group">
						<label for="meta-desc" class="field-label">Default Meta Description</label>
						<textarea
							id="meta-desc"
							bind:value={settings.defaultMetaDescription}
							class="field-textarea"
							rows="3"
							placeholder="Default description for pages without custom meta"
						></textarea>
						<span class="field-hint">{settings.defaultMetaDescription.length}/160 characters</span>
					</div>

					<div class="field-group">
						<label for="robots-default" class="field-label">Default Robots Directive</label>
						<select id="robots-default" bind:value={settings.robotsDefault} class="field-select">
							<option value="index, follow">Index, Follow</option>
							<option value="noindex, follow">No Index, Follow</option>
							<option value="index, nofollow">Index, No Follow</option>
							<option value="noindex, nofollow">No Index, No Follow</option>
						</select>
					</div>
				</div>

				<div class="settings-card">
					<h2 class="card-title">Search Engine Verification</h2>

					<div class="field-group">
						<label for="google-verify" class="field-label">
							<IconBrandGoogle size={16} />
							Google Site Verification
						</label>
						<input
							id="google-verify"
							type="text"
							bind:value={settings.googleSiteVerification}
							class="field-input"
							placeholder="Google verification code"
						/>
					</div>

					<div class="field-group">
						<label for="bing-verify" class="field-label">Bing Site Verification</label>
						<input
							id="bing-verify"
							type="text"
							bind:value={settings.bingSiteVerification}
							class="field-input"
							placeholder="Bing verification code"
						/>
					</div>
				</div>
			</div>
		{/if}

		<!-- Structured Data Tab -->
		{#if activeTab === 'structured'}
			<div class="structured-data-section">
				<div class="section-header">
					<h2 class="section-title">JSON-LD Schema Templates</h2>
					<p class="section-desc">
						Configure structured data templates for rich search results. Use placeholders like
						{'{{title}}'} for dynamic content.
					</p>
				</div>

				{#if editingTemplate}
					<div class="template-editor" in:fly={{ y: 10, duration: 200 }}>
						<div class="editor-header">
							<h3>Editing: {editingTemplate.name}</h3>
							<div class="editor-actions">
								<button
									class="btn-secondary"
									onclick={() => {
										editingTemplate = null;
										templateJson = '';
									}}
								>
									Cancel
								</button>
								<button class="btn-primary" onclick={saveTemplate}>
									<IconCheck size={16} />
									Save Template
								</button>
							</div>
						</div>
						<textarea class="json-editor" bind:value={templateJson} spellcheck="false" rows="20"
						></textarea>
					</div>
				{:else}
					<div class="templates-grid">
						{#each structuredDataTemplates as template}
							<div class="template-card" class:inactive={!template.isActive}>
								<div class="template-header">
									<div class="template-info">
										<span class="template-type">{template.type}</span>
										<h3 class="template-name">{template.name}</h3>
									</div>
									<label class="toggle">
										<input
											type="checkbox"
											checked={template.isActive}
											onchange={() => toggleTemplate(template.id)}
										/>
										<span class="toggle-slider"></span>
									</label>
								</div>
								<pre class="template-preview">{JSON.stringify(template.template, null, 2).slice(
										0,
										200
									)}...</pre>
								<button class="btn-edit" onclick={() => editTemplate(template)}>
									<IconCode size={14} />
									Edit Template
								</button>
							</div>
						{/each}
					</div>
				{/if}
			</div>
		{/if}

		<!-- Sitemap Tab -->
		{#if activeTab === 'sitemap'}
			<div class="sitemap-section">
				<div class="settings-grid">
					<div class="settings-card">
						<h2 class="card-title">Sitemap Settings</h2>

						<div class="field-group">
							<label class="toggle-field">
								<input type="checkbox" bind:checked={settings.sitemapEnabled} />
								<span class="toggle-slider"></span>
								<span class="toggle-label">Enable XML Sitemap</span>
							</label>
						</div>

						<div class="field-row">
							<div class="field-group">
								<label for="change-freq" class="field-label">Default Change Frequency</label>
								<select
									id="change-freq"
									bind:value={settings.sitemapChangeFreq}
									class="field-select"
								>
									<option value="always">Always</option>
									<option value="hourly">Hourly</option>
									<option value="daily">Daily</option>
									<option value="weekly">Weekly</option>
									<option value="monthly">Monthly</option>
									<option value="yearly">Yearly</option>
									<option value="never">Never</option>
								</select>
							</div>

							<div class="field-group">
								<label for="priority" class="field-label">Default Priority</label>
								<input
									id="priority"
									type="number"
									min="0"
									max="1"
									step="0.1"
									bind:value={settings.sitemapPriority}
									class="field-input"
								/>
							</div>
						</div>

						<button class="btn-action" onclick={regenerateSitemap} disabled={isSaving}>
							<IconRefresh size={16} />
							Regenerate Sitemap
						</button>
					</div>

					<div class="settings-card">
						<h2 class="card-title">Excluded Paths</h2>
						<p class="card-desc">
							These paths will not be included in the sitemap. Supports wildcards (*).
						</p>

						<div class="excluded-paths">
							{#each sitemapExcludedPaths as path}
								<div class="path-item">
									<code>{path}</code>
									<button class="btn-remove" onclick={() => removeExcludedPath(path)}>
										&times;
									</button>
								</div>
							{/each}
						</div>

						<button class="btn-add-path" onclick={addExcludedPath}> + Add Path </button>
					</div>

					<div class="settings-card full-width">
						<h2 class="card-title">Sitemap Preview</h2>
						<div class="sitemap-preview">
							<div class="preview-header">
								<span class="preview-url">/sitemap.xml</span>
								<a href="/sitemap.xml" target="_blank" class="btn-view">
									<IconWorld size={14} />
									View Sitemap
								</a>
							</div>
							<pre class="preview-content">&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"&gt;
  &lt;url&gt;
    &lt;loc&gt;https://revolutiontradingpros.com/&lt;/loc&gt;
    &lt;lastmod&gt;2026-01-27&lt;/lastmod&gt;
    &lt;changefreq&gt;weekly&lt;/changefreq&gt;
    &lt;priority&gt;1.0&lt;/priority&gt;
  &lt;/url&gt;
  &lt;url&gt;
    &lt;loc&gt;https://revolutiontradingpros.com/courses&lt;/loc&gt;
    &lt;lastmod&gt;2026-01-25&lt;/lastmod&gt;
    &lt;changefreq&gt;weekly&lt;/changefreq&gt;
    &lt;priority&gt;0.8&lt;/priority&gt;
  &lt;/url&gt;
  &lt;!-- ... more URLs ... --&gt;
&lt;/urlset&gt;</pre>
						</div>
					</div>
				</div>
			</div>
		{/if}

		<!-- Robots.txt Tab -->
		{#if activeTab === 'robots'}
			<div class="robots-section">
				<div class="settings-card full-width">
					<div class="card-header">
						<h2 class="card-title">Robots.txt Editor</h2>
						<a href="/robots.txt" target="_blank" class="btn-view">
							<IconWorld size={14} />
							View Live File
						</a>
					</div>
					<p class="card-desc">
						Control how search engines crawl your site. Be careful with changes as they can affect
						your site's visibility.
					</p>

					<textarea class="robots-editor" bind:value={robotsTxt} spellcheck="false" rows="20"
					></textarea>

					<div class="robots-tips">
						<h4>Common Directives</h4>
						<ul>
							<li><code>User-agent: *</code> - Apply rules to all bots</li>
							<li><code>Allow: /</code> - Allow crawling of all pages</li>
							<li><code>Disallow: /admin/</code> - Block crawling of admin pages</li>
							<li><code>Sitemap: URL</code> - Point to your sitemap</li>
						</ul>
					</div>
				</div>
			</div>
		{/if}

		<!-- Social Tab -->
		{#if activeTab === 'social'}
			<div class="settings-grid">
				<div class="settings-card">
					<h2 class="card-title">
						<IconBrandFacebook size={20} />
						Open Graph (Facebook)
					</h2>

					<div class="field-group">
						<label for="og-image" class="field-label">Default OG Image</label>
						<div class="image-upload">
							<input
								id="og-image"
								type="text"
								bind:value={settings.defaultOgImage}
								class="field-input"
								placeholder="/images/og-default.jpg"
							/>
						</div>
						<span class="field-hint">Recommended size: 1200x630 pixels</span>
					</div>

					<div class="field-group">
						<label for="fb-app-id" class="field-label">Facebook App ID</label>
						<input
							id="fb-app-id"
							type="text"
							bind:value={settings.facebookAppId}
							class="field-input"
							placeholder="Optional: Your Facebook App ID"
						/>
					</div>

					<div class="og-preview">
						<h4>Preview</h4>
						<div class="og-card">
							<div class="og-image">
								{#if settings.defaultOgImage}
									<img src={settings.defaultOgImage} alt="OG Preview" />
								{:else}
									<div class="og-placeholder">No image set</div>
								{/if}
							</div>
							<div class="og-content">
								<span class="og-site">revolutiontradingpros.com</span>
								<h5 class="og-title">{settings.siteName}</h5>
								<p class="og-desc">{settings.siteDescription}</p>
							</div>
						</div>
					</div>
				</div>

				<div class="settings-card">
					<h2 class="card-title">
						<IconBrandTwitter size={20} />
						Twitter Card
					</h2>

					<div class="field-group">
						<label for="twitter-handle" class="field-label">Twitter Handle</label>
						<input
							id="twitter-handle"
							type="text"
							bind:value={settings.twitterHandle}
							class="field-input"
							placeholder="@YourHandle"
						/>
					</div>

					<div class="twitter-preview">
						<h4>Preview</h4>
						<div class="twitter-card">
							<div class="twitter-image">
								{#if settings.defaultOgImage}
									<img src={settings.defaultOgImage} alt="Twitter Preview" />
								{:else}
									<div class="twitter-placeholder">No image set</div>
								{/if}
							</div>
							<div class="twitter-content">
								<h5 class="twitter-title">{settings.siteName}</h5>
								<p class="twitter-desc">{settings.siteDescription}</p>
								<span class="twitter-site">{settings.twitterHandle}</span>
							</div>
						</div>
					</div>
				</div>

				<div class="settings-card">
					<h2 class="card-title">
						<IconChartLine size={20} />
						Analytics Integration
					</h2>

					<div class="field-group">
						<label for="ga-id" class="field-label">Google Analytics ID</label>
						<input id="ga-id" type="text" class="field-input" placeholder="G-XXXXXXXXXX" />
					</div>

					<div class="field-group">
						<label for="gtm-id" class="field-label">Google Tag Manager ID</label>
						<input id="gtm-id" type="text" class="field-input" placeholder="GTM-XXXXXXX" />
					</div>

					<div class="analytics-note">
						<IconAlertTriangle size={16} />
						<span>Analytics tracking codes are injected site-wide. Ensure GDPR compliance.</span>
					</div>
				</div>
			</div>
		{/if}
	</div>
</div>

<style>
	.seo-page {
		padding: 1.5rem;
		max-width: 1400px;
		margin: 0 auto;
	}

	/* Header */
	.page-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		margin-bottom: 1.5rem;
	}

	.header-content {
		display: flex;
		align-items: center;
		gap: 1rem;
	}

	.header-content :global(.header-icon) {
		color: var(--primary-500);
	}

	.page-title {
		font-size: 1.5rem;
		font-weight: 700;
		color: #f1f5f9;
		margin: 0;
	}

	.page-subtitle {
		font-size: 0.875rem;
		color: #64748b;
		margin: 0.25rem 0 0 0;
	}

	.btn-primary {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.625rem 1rem;
		background: linear-gradient(135deg, var(--primary-500), #d4a600);
		border: none;
		border-radius: 0.5rem;
		color: #0f172a;
		font-weight: 600;
		font-size: 0.875rem;
		cursor: pointer;
		transition: all 0.15s;
	}

	.btn-primary:hover:not(:disabled) {
		transform: translateY(-1px);
		box-shadow: 0 4px 12px rgba(230, 184, 0, 0.3);
	}

	.btn-primary:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	/* Banners */
	.success-banner,
	.error-banner {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		padding: 1rem 1.25rem;
		border-radius: 0.5rem;
		margin-bottom: 1.5rem;
	}

	.success-banner {
		background: rgba(34, 197, 94, 0.1);
		border: 1px solid rgba(34, 197, 94, 0.3);
		color: #4ade80;
	}

	.error-banner {
		background: rgba(239, 68, 68, 0.1);
		border: 1px solid rgba(239, 68, 68, 0.3);
		color: #f87171;
	}

	.error-banner button {
		margin-left: auto;
		padding: 0.375rem 0.75rem;
		background: transparent;
		border: 1px solid rgba(239, 68, 68, 0.3);
		border-radius: 0.375rem;
		color: #f87171;
		font-size: 0.8125rem;
		cursor: pointer;
	}

	/* Tabs */
	.tabs {
		display: flex;
		gap: 0.25rem;
		padding: 0.5rem;
		background: rgba(30, 41, 59, 0.3);
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-radius: 0.75rem 0.75rem 0 0;
		border-bottom: none;
	}

	.tab-btn {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.625rem 1rem;
		background: transparent;
		border: none;
		border-radius: 0.5rem;
		color: #94a3b8;
		font-size: 0.875rem;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.15s;
	}

	.tab-btn:hover {
		background: rgba(51, 65, 85, 0.3);
		color: #f1f5f9;
	}

	.tab-btn.active {
		background: rgba(230, 184, 0, 0.15);
		color: var(--primary-500);
	}

	/* Tab Content */
	.tab-content {
		background: rgba(30, 41, 59, 0.3);
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-top: none;
		border-radius: 0 0 0.75rem 0.75rem;
		padding: 1.5rem;
	}

	/* Settings Grid */
	.settings-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
		gap: 1.5rem;
	}

	.settings-card {
		background: rgba(0, 0, 0, 0.2);
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-radius: 0.75rem;
		padding: 1.25rem;
	}

	.settings-card.full-width {
		grid-column: 1 / -1;
	}

	.card-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		margin-bottom: 0.5rem;
	}

	.card-title {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		font-size: 1rem;
		font-weight: 600;
		color: #f1f5f9;
		margin: 0 0 1rem 0;
	}

	.card-desc {
		font-size: 0.8125rem;
		color: #64748b;
		margin: 0 0 1rem 0;
	}

	/* Fields */
	.field-group {
		margin-bottom: 1.25rem;
	}

	.field-row {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
		gap: 1rem;
	}

	.field-label {
		display: flex;
		align-items: center;
		gap: 0.375rem;
		font-size: 0.8125rem;
		font-weight: 600;
		color: #cbd5e1;
		margin-bottom: 0.5rem;
	}

	.field-input,
	.field-textarea,
	.field-select {
		width: 100%;
		padding: 0.625rem 0.875rem;
		background: rgba(0, 0, 0, 0.2);
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-radius: 0.5rem;
		color: #f1f5f9;
		font-size: 0.875rem;
		transition: border-color 0.15s;
	}

	.field-input:focus,
	.field-textarea:focus,
	.field-select:focus {
		outline: none;
		border-color: var(--primary-500);
	}

	.field-textarea {
		resize: vertical;
	}

	.field-hint {
		display: block;
		font-size: 0.75rem;
		color: #64748b;
		margin-top: 0.375rem;
	}

	/* Toggle */
	.toggle,
	.toggle-field {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		cursor: pointer;
	}

	.toggle input,
	.toggle-field input {
		display: none;
	}

	.toggle-slider {
		position: relative;
		width: 44px;
		height: 24px;
		background: rgba(51, 65, 85, 0.5);
		border-radius: 12px;
		transition: all 0.2s;
	}

	.toggle-slider::after {
		content: '';
		position: absolute;
		top: 2px;
		left: 2px;
		width: 20px;
		height: 20px;
		background: #94a3b8;
		border-radius: 50%;
		transition: all 0.2s;
	}

	.toggle input:checked + .toggle-slider,
	.toggle-field input:checked + .toggle-slider {
		background: rgba(230, 184, 0, 0.3);
	}

	.toggle input:checked + .toggle-slider::after,
	.toggle-field input:checked + .toggle-slider::after {
		transform: translateX(20px);
		background: var(--primary-500);
	}

	.toggle-label {
		font-size: 0.875rem;
		color: #f1f5f9;
	}

	/* Buttons */
	.btn-secondary {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.5rem 1rem;
		background: rgba(51, 65, 85, 0.3);
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-radius: 0.5rem;
		color: #94a3b8;
		font-weight: 500;
		font-size: 0.875rem;
		cursor: pointer;
		transition: all 0.15s;
	}

	.btn-secondary:hover {
		background: rgba(51, 65, 85, 0.5);
		color: #f1f5f9;
	}

	.btn-action {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.625rem 1rem;
		background: rgba(230, 184, 0, 0.15);
		border: 1px solid rgba(230, 184, 0, 0.3);
		border-radius: 0.5rem;
		color: var(--primary-500);
		font-weight: 500;
		font-size: 0.875rem;
		cursor: pointer;
		transition: all 0.15s;
	}

	.btn-action:hover:not(:disabled) {
		background: rgba(230, 184, 0, 0.25);
	}

	.btn-action:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.btn-view {
		display: flex;
		align-items: center;
		gap: 0.375rem;
		padding: 0.375rem 0.75rem;
		background: transparent;
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-radius: 0.375rem;
		color: #94a3b8;
		font-size: 0.8125rem;
		text-decoration: none;
		cursor: pointer;
		transition: all 0.15s;
	}

	.btn-view:hover {
		background: rgba(51, 65, 85, 0.3);
		color: #f1f5f9;
	}

	/* Structured Data */
	.section-header {
		margin-bottom: 1.5rem;
	}

	.section-title {
		font-size: 1.125rem;
		font-weight: 600;
		color: #f1f5f9;
		margin: 0 0 0.5rem 0;
	}

	.section-desc {
		font-size: 0.875rem;
		color: #64748b;
		margin: 0;
	}

	.templates-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
		gap: 1rem;
	}

	.template-card {
		background: rgba(0, 0, 0, 0.2);
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-radius: 0.75rem;
		padding: 1rem;
		transition: opacity 0.15s;
	}

	.template-card.inactive {
		opacity: 0.6;
	}

	.template-header {
		display: flex;
		align-items: flex-start;
		justify-content: space-between;
		margin-bottom: 1rem;
	}

	.template-type {
		display: inline-block;
		padding: 0.125rem 0.5rem;
		background: rgba(230, 184, 0, 0.15);
		border-radius: 0.25rem;
		font-size: 0.6875rem;
		font-weight: 600;
		color: var(--primary-500);
		text-transform: uppercase;
		margin-bottom: 0.25rem;
	}

	.template-name {
		font-size: 0.9375rem;
		font-weight: 600;
		color: #f1f5f9;
		margin: 0;
	}

	.template-preview {
		background: rgba(0, 0, 0, 0.3);
		border-radius: 0.375rem;
		padding: 0.75rem;
		font-family: 'Fira Code', 'Monaco', monospace;
		font-size: 0.6875rem;
		color: #94a3b8;
		overflow: hidden;
		white-space: pre-wrap;
		word-break: break-all;
		max-height: 100px;
		margin-bottom: 1rem;
	}

	.btn-edit {
		display: flex;
		align-items: center;
		gap: 0.375rem;
		width: 100%;
		padding: 0.5rem;
		background: transparent;
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-radius: 0.375rem;
		color: #94a3b8;
		font-size: 0.8125rem;
		cursor: pointer;
		justify-content: center;
		transition: all 0.15s;
	}

	.btn-edit:hover {
		background: rgba(51, 65, 85, 0.3);
		color: #f1f5f9;
	}

	.template-editor {
		background: rgba(0, 0, 0, 0.2);
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-radius: 0.75rem;
		padding: 1.25rem;
	}

	.editor-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		margin-bottom: 1rem;
	}

	.editor-header h3 {
		font-size: 1rem;
		font-weight: 600;
		color: #f1f5f9;
		margin: 0;
	}

	.editor-actions {
		display: flex;
		gap: 0.5rem;
	}

	.json-editor {
		width: 100%;
		padding: 1rem;
		background: rgba(0, 0, 0, 0.3);
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-radius: 0.5rem;
		color: #f1f5f9;
		font-family: 'Fira Code', 'Monaco', monospace;
		font-size: 0.875rem;
		line-height: 1.5;
		resize: vertical;
	}

	.json-editor:focus {
		outline: none;
		border-color: var(--primary-500);
	}

	/* Sitemap */
	.excluded-paths {
		display: flex;
		flex-wrap: wrap;
		gap: 0.5rem;
		margin-bottom: 1rem;
	}

	.path-item {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.375rem 0.75rem;
		background: rgba(0, 0, 0, 0.2);
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-radius: 0.375rem;
	}

	.path-item code {
		font-family: 'Fira Code', 'Monaco', monospace;
		font-size: 0.8125rem;
		color: #94a3b8;
	}

	.btn-remove {
		background: none;
		border: none;
		color: #64748b;
		cursor: pointer;
		font-size: 1rem;
		line-height: 1;
	}

	.btn-remove:hover {
		color: #f87171;
	}

	.btn-add-path {
		padding: 0.5rem 1rem;
		background: transparent;
		border: 1px dashed rgba(51, 65, 85, 0.5);
		border-radius: 0.375rem;
		color: #64748b;
		font-size: 0.8125rem;
		cursor: pointer;
		transition: all 0.15s;
	}

	.btn-add-path:hover {
		border-color: var(--primary-500);
		color: var(--primary-500);
	}

	.sitemap-preview,
	.robots-editor {
		background: rgba(0, 0, 0, 0.3);
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-radius: 0.5rem;
		overflow: hidden;
	}

	.preview-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: 0.75rem 1rem;
		background: rgba(0, 0, 0, 0.2);
		border-bottom: 1px solid rgba(51, 65, 85, 0.5);
	}

	.preview-url {
		font-family: 'Fira Code', 'Monaco', monospace;
		font-size: 0.8125rem;
		color: var(--primary-500);
	}

	.preview-content {
		padding: 1rem;
		font-family: 'Fira Code', 'Monaco', monospace;
		font-size: 0.8125rem;
		color: #94a3b8;
		line-height: 1.6;
		margin: 0;
		overflow-x: auto;
	}

	/* Robots */
	.robots-editor {
		width: 100%;
		padding: 1rem;
		color: #f1f5f9;
		font-family: 'Fira Code', 'Monaco', monospace;
		font-size: 0.875rem;
		line-height: 1.6;
		resize: vertical;
		border: 1px solid rgba(51, 65, 85, 0.5);
		border-radius: 0.5rem;
		background: rgba(0, 0, 0, 0.3);
	}

	.robots-editor:focus {
		outline: none;
		border-color: var(--primary-500);
	}

	.robots-tips {
		margin-top: 1rem;
		padding: 1rem;
		background: rgba(0, 0, 0, 0.2);
		border-radius: 0.5rem;
	}

	.robots-tips h4 {
		font-size: 0.875rem;
		font-weight: 600;
		color: #f1f5f9;
		margin: 0 0 0.75rem 0;
	}

	.robots-tips ul {
		margin: 0;
		padding-left: 1.25rem;
	}

	.robots-tips li {
		font-size: 0.8125rem;
		color: #94a3b8;
		margin-bottom: 0.375rem;
	}

	.robots-tips code {
		padding: 0.125rem 0.375rem;
		background: rgba(0, 0, 0, 0.3);
		border-radius: 0.25rem;
		font-family: 'Fira Code', 'Monaco', monospace;
		font-size: 0.75rem;
		color: var(--primary-500);
	}

	/* Social */
	.og-preview,
	.twitter-preview {
		margin-top: 1.5rem;
	}

	.og-preview h4,
	.twitter-preview h4 {
		font-size: 0.8125rem;
		font-weight: 600;
		color: #64748b;
		margin: 0 0 0.75rem 0;
		text-transform: uppercase;
	}

	.og-card,
	.twitter-card {
		background: #ffffff;
		border-radius: 0.5rem;
		overflow: hidden;
		max-width: 400px;
	}

	.og-image,
	.twitter-image {
		height: 200px;
		background: #f3f4f6;
	}

	.og-image img,
	.twitter-image img {
		width: 100%;
		height: 100%;
		object-fit: cover;
	}

	.og-placeholder,
	.twitter-placeholder {
		display: flex;
		align-items: center;
		justify-content: center;
		height: 100%;
		color: #9ca3af;
		font-size: 0.875rem;
	}

	.og-content,
	.twitter-content {
		padding: 0.75rem;
	}

	.og-site {
		font-size: 0.75rem;
		color: #6b7280;
		text-transform: uppercase;
	}

	.og-title,
	.twitter-title {
		font-size: 1rem;
		font-weight: 600;
		color: #1f2937;
		margin: 0.25rem 0;
	}

	.og-desc,
	.twitter-desc {
		font-size: 0.875rem;
		color: #6b7280;
		margin: 0;
		display: -webkit-box;
		-webkit-line-clamp: 2;
		-webkit-box-orient: vertical;
		overflow: hidden;
	}

	.twitter-site {
		font-size: 0.8125rem;
		color: #6b7280;
	}

	.analytics-note {
		display: flex;
		align-items: flex-start;
		gap: 0.5rem;
		padding: 0.75rem;
		background: rgba(234, 179, 8, 0.1);
		border: 1px solid rgba(234, 179, 8, 0.3);
		border-radius: 0.5rem;
		font-size: 0.8125rem;
		color: #fbbf24;
	}

	/* Responsive */
	@media (max-width: 768px) {
		.seo-page {
			padding: 1rem;
		}

		.page-header {
			flex-direction: column;
			align-items: flex-start;
			gap: 1rem;
		}

		.tabs {
			overflow-x: auto;
			-webkit-overflow-scrolling: touch;
		}

		.tab-btn span {
			display: none;
		}

		.settings-grid {
			grid-template-columns: 1fr;
		}

		.templates-grid {
			grid-template-columns: 1fr;
		}
	}
</style>
