/**
 * Type declarations for @tabler/icons-svelte
 * The package has incomplete TS definitions - this fixes all icon imports
 */
declare module '@tabler/icons-svelte' {
	import type { Component } from 'svelte';

	interface IconProps {
		size?: number | string;
		stroke?: number | string;
		color?: string;
		class?: string;
		style?: string;
		'aria-hidden'?: boolean | string;
		'aria-label'?: string;
		[key: string]: unknown;
	}

	type IconComponent = Component<IconProps>;

	// Export all icons as any to bypass TS checking
	export const IconAB: IconComponent;
	export const IconAB2: IconComponent;
	export const IconActivity: IconComponent;
	export const IconActivityHeartbeat: IconComponent;
	export const IconAdjustments: IconComponent;
	export const IconAdjustmentsAlt: IconComponent;
	export const IconAdjustmentsHorizontal: IconComponent;
	export const IconAlertCircle: IconComponent;
	export const IconAlertTriangle: IconComponent;
	export const IconAntenna: IconComponent;
	export const IconArrowDown: IconComponent;
	export const IconArrowDownRight: IconComponent;
	export const IconArrowLeft: IconComponent;
	export const IconArrowRight: IconComponent;
	export const IconArrowUp: IconComponent;
	export const IconArrowUpRight: IconComponent;
	export const IconArrowsLeftRight: IconComponent;
	export const IconArrowsSort: IconComponent;
	export const IconArrowsUpDown: IconComponent;
	export const IconAward: IconComponent;
	export const IconBadge: IconComponent;
	export const IconBell: IconComponent;
	export const IconBellRinging: IconComponent;
	export const IconBolt: IconComponent;
	export const IconBox: IconComponent;
	export const IconBrain: IconComponent;
	export const IconBrowser: IconComponent;
	export const IconBuilding: IconComponent;
	export const IconBuildingBank: IconComponent;
	export const IconBuildingSkyscraper: IconComponent;
	export const IconBulb: IconComponent;
	export const IconBullseye: IconComponent;
	export const IconCalculator: IconComponent;
	export const IconCalendar: IconComponent;
	export const IconCash: IconComponent;
	export const IconCashBanknote: IconComponent;
	export const IconCertificate: IconComponent;
	export const IconChartArea: IconComponent;
	export const IconChartArcs: IconComponent;
	export const IconChartBar: IconComponent;
	export const IconChartCandle: IconComponent;
	export const IconChartDonut: IconComponent;
	export const IconChartDots: IconComponent;
	export const IconChartHistogram: IconComponent;
	export const IconChartInfographic: IconComponent;
	export const IconChartLine: IconComponent;
	export const IconChartPie: IconComponent;
	export const IconChartRadar: IconComponent;
	export const IconCheck: IconComponent;
	export const IconChip: IconComponent;
	export const IconCircleCheck: IconComponent;
	export const IconCircleX: IconComponent;
	export const IconClick: IconComponent;
	export const IconClipboard: IconComponent;
	export const IconClock: IconComponent;
	export const IconCoin: IconComponent;
	export const IconCoins: IconComponent;
	export const IconCompass: IconComponent;
	export const IconCpu: IconComponent;
	export const IconCreditCard: IconComponent;
	export const IconCurrencyBitcoin: IconComponent;
	export const IconCurrencyDollar: IconComponent;
	export const IconCurrencyEthereum: IconComponent;
	export const IconCurrencyEuro: IconComponent;
	export const IconCursorText: IconComponent;
	export const IconDashboard: IconComponent;
	export const IconDatabase: IconComponent;
	export const IconDeviceAnalytics: IconComponent;
	export const IconDeviceDesktop: IconComponent;
	export const IconDeviceDesktopAnalytics: IconComponent;
	export const IconDeviceMobile: IconComponent;
	export const IconDevices: IconComponent;
	export const IconDiscount: IconComponent;
	export const IconDots: IconComponent;
	export const IconDotsVertical: IconComponent;
	export const IconEdit: IconComponent;
	export const IconExternalLink: IconComponent;
	export const IconEye: IconComponent;
	export const IconEyeCheck: IconComponent;
	export const IconEyeOff: IconComponent;
	export const IconFile: IconComponent;
	export const IconFileAnalytics: IconComponent;
	export const IconFilter: IconComponent;
	export const IconFlame: IconComponent;
	export const IconFlask: IconComponent;
	export const IconFocus: IconComponent;
	export const IconFocusCentered: IconComponent;
	export const IconFolder: IconComponent;
	export const IconGauge: IconComponent;
	export const IconGraph: IconComponent;
	export const IconHeartbeat: IconComponent;
	export const IconHome: IconComponent;
	export const IconHomeDollar: IconComponent;
	export const IconHourglass: IconComponent;
	export const IconInfoCircle: IconComponent;
	export const IconKey: IconComponent;
	export const IconLayersLinked: IconComponent;
	export const IconLeaf: IconComponent;
	export const IconList: IconComponent;
	export const IconListCheck: IconComponent;
	export const IconLoader: IconComponent;
	export const IconLocation: IconComponent;
	export const IconLock: IconComponent;
	export const IconLockOpen: IconComponent;
	export const IconMail: IconComponent;
	export const IconMap: IconComponent;
	export const IconMapPin: IconComponent;
	export const IconMedal: IconComponent;
	export const IconMoneybag: IconComponent;
	export const IconMouse: IconComponent;
	export const IconNetwork: IconComponent;
	export const IconPercentage: IconComponent;
	export const IconPhone: IconComponent;
	export const IconPigMoney: IconComponent;
	export const IconPlayerPlay: IconComponent;
	export const IconPlus: IconComponent;
	export const IconQuestionMark: IconComponent;
	export const IconRadar: IconComponent;
	export const IconRadar2: IconComponent;
	export const IconReceipt: IconComponent;
	export const IconReceiptTax: IconComponent;
	export const IconRefresh: IconComponent;
	export const IconRocket: IconComponent;
	export const IconScale: IconComponent;
	export const IconScan: IconComponent;
	export const IconSearch: IconComponent;
	export const IconServer: IconComponent;
	export const IconSettings: IconComponent;
	export const IconShield: IconComponent;
	export const IconShieldCheck: IconComponent;
	export const IconShieldLock: IconComponent;
	export const IconSignal: IconComponent;
	export const IconSliders: IconComponent;
	export const IconSpeedboat: IconComponent;
	export const IconStack: IconComponent;
	export const IconStar: IconComponent;
	export const IconStarFilled: IconComponent;
	export const IconTag: IconComponent;
	export const IconTarget: IconComponent;
	export const IconTargetArrow: IconComponent;
	export const IconTimeline: IconComponent;
	export const IconTool: IconComponent;
	export const IconTools: IconComponent;
	export const IconTrash: IconComponent;
	export const IconTrendingDown: IconComponent;
	export const IconTrendingDown2: IconComponent;
	export const IconTrendingDown3: IconComponent;
	export const IconTrendingUp: IconComponent;
	export const IconTrendingUp2: IconComponent;
	export const IconTrendingUp3: IconComponent;
	export const IconTrophy: IconComponent;
	export const IconUser: IconComponent;
	export const IconUserPlus: IconComponent;
	export const IconUsers: IconComponent;
	export const IconUsersGroup: IconComponent;
	export const IconWifi: IconComponent;
	export const IconWorld: IconComponent;
	export const IconX: IconComponent;
	export const IconZoomCheck: IconComponent;
	export const IconZoomIn: IconComponent;
	export const IconZoomMoney: IconComponent;
	export const IconZoomOut: IconComponent;

	// Catch-all for any other icons
	const icons: Record<string, IconComponent>;
	export default icons;
}
